/* A lexical scanner for NetHack generated by flex */

/* Scanner skeleton version:
 * flexhack.skl 3.3.0 (from .../flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47)
 */
#define FLEXHACK_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include "config.h"
#define yyconst const	/* some code inserted by flex will refer to yyconst */

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* Return all but the first 'n' matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */

int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void FDECL(yyrestart, (FILE *));

void FDECL(yy_switch_to_buffer, (YY_BUFFER_STATE));
void NDECL(yy_load_buffer_state);
YY_BUFFER_STATE FDECL(yy_create_buffer, (FILE *,int));
void FDECL(yy_delete_buffer, (YY_BUFFER_STATE));
void FDECL(yy_init_buffer, (YY_BUFFER_STATE,FILE *));
void FDECL(yy_flush_buffer, (YY_BUFFER_STATE));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

static genericptr_t FDECL(yy_flex_alloc, (yy_size_t));
static genericptr_t FDECL(yy_flex_realloc2, (genericptr_t,yy_size_t,int));
static void FDECL(yy_flex_free, (genericptr_t));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type NDECL(yy_get_previous_state);
static yy_state_type FDECL(yy_try_NUL_trans, (yy_state_type));
static int NDECL(yy_get_next_buffer);
static void FDECL(yy_fatal_error, (const char *));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
static yyconst short int yy_accept[633] =
    {   0,
        0,    0,    0,    0,  113,  111,  108,  107,  111,  111,
      111,  105,    4,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
        2,  108,  111,  111,  105,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  108,    0,  106,
        0,    0,  105,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   87,    0,    0,
        3,    0,    2,  108,    0,  105,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,  110,    0,  110,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   72,    0,    0,
       67,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   65,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  109,    0,    0,
        0,    0,    0,   17,    0,    0,    0,    0,    0,   40,
        0,    0,    0,    6,    0,    0,   42,    0,    0,    0,
       33,    0,    0,    0,   36,   32,    0,    0,    0,   16,

        0,    0,  104,    0,    0,    0,    0,    0,    0,    0,
        0,   93,    0,    0,    0,    0,    0,    0,   88,   91,
       51,    0,    0,    0,    0,    0,    0,   60,    0,    0,
        0,    0,    0,   94,    0,    0,    0,    0,    0,    0,
       55,    0,    0,    0,   45,    0,    0,    0,    0,    0,
        0,    0,    0,   90,    0,    0,    0,   53,   12,    0,
        0,    0,    0,   25,    0,    0,    0,    0,    0,    0,
       10,    0,    0,    0,    0,    8,    0,    0,    0,    7,
        0,    0,    0,    0,    0,    0,   27,    0,    0,    0,
       59,   86,    0,    0,   80,    0,    0,    0,    0,   74,

        0,    0,    0,    0,    0,   89,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   50,    0,    0,    0,   58,    0,   64,    0,    0,
        0,   52,    0,    0,   68,    0,    0,   30,   43,    0,
        0,    0,    0,    0,    0,    0,   26,    0,    0,    0,
        0,    0,   13,   28,    0,   21,    0,    0,    0,    0,
       79,    0,   66,   49,   62,   46,    0,    0,   97,    0,
       69,    0,    0,    0,    0,    0,   47,    0,    0,    0,
        0,    0,    0,   48,  101,    0,    0,   56,    0,   54,
        0,    0,   85,    0,    0,    1,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    5,   15,    0,    0,    0,
       37,    0,   20,    0,   95,    0,    0,   92,    0,    0,
        0,   78,    0,    0,    0,    0,   57,   73,   71,    0,
        0,    0,   84,    0,    0,    0,    0,   39,    0,    0,
       31,   11,    9,   19,    0,    0,    0,    0,    0,    0,
        0,  102,    0,    0,    0,    0,    0,    0,    0,    0,
       83,    0,    0,   77,    0,   96,   70,   14,    0,   41,
        0,    0,    0,    0,    0,    0,    0,   75,   98,   61,
        0,  100,   44,   81,   82,    0,    0,    0,   18,    0,
        0,    0,    0,    0,    0,    0,   63,    0,   99,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   34,
       35,    0,    0,    0,    0,    0,   76,  103,    0,    0,
        0,   24,    0,    0,    0,   22,    0,    0,   23,   29,
       38,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    1,    8,    1,
        1,    1,    9,    1,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
        1,   30,   31,   32,   33,   34,   35,    1,   36,   37,
       38,   39,   40,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,    1,   58,   59,   60,   61,   62,   63,    1,
        1,    1,   11,   11,   11,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    2,    3,    2,    1,    2,    1,    1,    2,    2,
        2,    2,    1,    2,    2,    2,    1,    1,    2,    1,
        2,    2,    1,    2,    2,    1,    1,    1,    2,    1,
        2,    2,    1,    1,    2,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[638] =
    {   0,
        0,   58,   82,   61,  781,  782,   64,  782,  775,  740,
      766,  765,  782,  751,  745,   44,   41,  747,   45,   61,
      746,   60,   62,   67,  757,  743,   91,   90,   90,  756,
       71,   71,   75,   86,   21,   60,   68,   84,   95,  102,
       92,  103,  103,  111,  108,   69,   97,  723,  765,  141,
      782,  163,  160,  168,  170,  172,  174,  181,  740,  183,
      176,  187,  185,  190,  196,  192,  224,  213,  761,  782,
      757,  756,  751,  730,  747,  746,  180,  731,  744,  737,
      742,  722,  726,  728,  730,  734,  716,  712,  717,  720,
      720,  192,  722,  201,  717,  723,  714,  714,  726,  724,

      713,  723,  711,  212,  184,  182,  692,  681,  691,  686,
      671,  674,  671,  673,  685,  670,  126,  667,  661,  664,
      663,  673,  667,  666,  167,  659,  654,  190,  656,  671,
      204,  656,  658,  651,  212,  660,  664,  667,  666,  652,
      658,  650,  206,  643,  646,  641,  197,  782,  642,  697,
      782,  232,  782,  271,  274,  276,  278,  280,  248,  282,
      284,  287,  289,  295,  782,    0,  782,  691,  690,  683,
      669,  668,  662,  663,  662,  656,  660,  669,  661,  661,
      669,  653,  667,  665,  664,  650,  649,  661,  664,  636,
      658,  650,  642,  656,  650,  645,  646,  647,  638,  649,

      637,  640,  267,  616,  621,  606,  615,  608,  600,  598,
      605,  601,  595,  598,  594,  599,  591,  591,  594,  588,
      587,  588,  586,  591,  596,  597,  581,  782,  580,  581,
      782,  586,  591,  580,  592,  582,  574,  572,  578,  574,
      575,  249,  568,  581,  580,  570,  580,  579,  577,  572,
      576,  561,  568,  557,  782,  570,  554,  564,  563,  552,
      608,  297,  302,  584,  306,  310,  313,  782,  579,  592,
      591,  592,  583,  782,  589,  589,  571,  569,  582,  782,
      558,  580,  572,  561,  581,  562,  782,  564,  289,  576,
      782,  577,  562,  561,  782,  782,  558,  559,  557,  782,

      563,  313,  782,  529,  525,  524,  535,  534,  520,  522,
      531,  782,  530,  516,  528,  523,  530,  525,  782,  782,
      782,  528,  523,  522,  557,  519,  515,  782,  518,  517,
      520,  506,  509,  782,  499,  500,  507,  500,  513,  498,
      782,  504,  499,  507,  782,  504,  503,  492,  487,  486,
      485,  489,  494,  782,  484,  488,  480,  782,  782,  319,
      525,  321,  325,  782,  517,  519,  514,  518,  504,  499,
      782,  518,  499,  504,  499,  782,  514,  507,  508,  782,
      503,  510,  491,  497,  495,  493,  782,  491,  490,  498,
      782,  782,  470,  458,  782,  468,  459,  457,  453,  782,

      465,  461,  458,  462,  444,  782,  460,  272,  451,  450,
      454,  456,  440,  440,  452,  451,  454,  447,  436,  436,
      450,  782,  445,  430,  442,  782,  434,  782,  426,  427,
      439,  782,  425,  430,  782,  453,  331,  782,  782,  454,
      452,  457,  456,  455,  446,  461,  782,  449,  455,  442,
      451,  439,  782,  782,  428,  782,  442,  437,  430,  423,
      782,  419,  782,  782,  782,  782,  408,  407,  782,  415,
      782,  414,  409,  402,  411,  406,  782,  394,  394,  409,
      394,  398,  395,  782,  782,  396,  391,  782,  386,  782,
      392,  395,  782,  398,  397,  782,  333,  424,  411,  423,

      412,  411,  401,  407,  411,  782,  782,  414,  402,  315,
      782,  400,  782,  378,  782,  384,  383,  782,  381,  379,
      370,  782,  369,  366,  377,  362,  782,  782,  782,  371,
      364,  366,  782,  370,  372,  371,  385,  782,  394,  393,
      782,  782,  782,  782,  398,  376,  382,  381,  393,  382,
      365,  782,  360,  359,  343,  353,  343,  345,  353,  340,
      782,  349,  338,  782,  346,  782,  782,  782,  376,  782,
      378,  378,  361,  363,  366,  374,  357,  782,  782,  782,
      326,  782,  782,  782,  782,  330,  324,  323,  782,  357,
      343,  337,  335,  347,  348,  345,  782,  316,  782,  315,

      342,  334,  336,  325,  340,  337,  334,  307,  303,  782,
      782,  329,  327,  310,  309,  317,  782,  782,  309,  289,
      271,  782,  219,  191,  169,  782,   89,   68,  782,  782,
      782,  782,  369,  372,  374,  376,  379
    } ;

static yyconst short int yy_def[638] =
    {   0,
      632,    1,    1,    3,  632,  632,  632,  632,  633,  634,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  635,  632,
      632,  636,  636,  636,  636,  636,  636,  636,  632,  636,
      636,  636,  636,  636,  636,  636,  635,  632,  633,  632,
      632,  637,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  635,
      632,  632,  632,  636,  636,  636,  636,  636,  632,  636,
      636,  636,  636,  636,  632,   67,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  636,  636,  632,  636,  636,  636,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  636,
      632,  636,  636,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  636,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  636,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,    0,  632,  632,  632,  632,  632
    } ;

static yyconst short int yy_nxt[846] =
    {   0,
        6,    7,    8,    7,    9,    6,    6,   10,   11,   11,
        6,   12,   13,   14,   15,   16,   17,   18,   19,   20,
        6,   21,    6,    6,   22,   23,   24,   25,   26,   27,
       28,   29,    6,    6,   30,    6,    6,   31,    6,    6,
        6,   32,   33,   34,   35,   36,   37,    6,   38,    6,
        6,    6,   39,   40,   41,   42,   43,   44,   45,   46,
       47,    6,   48,   49,   76,   68,   67,   68,   78,   81,
       79,   77,   82,   86,  104,   88,  119,   87,   83,   89,
       91,  120,  105,   50,   51,   52,   50,   53,   84,   90,
       54,   54,   53,   55,   92,   56,   57,   58,  631,   59,

       60,  121,   53,   61,   95,   53,   62,  101,   96,  123,
       63,   98,   64,   65,  122,  630,   66,  124,   97,  102,
       53,   99,  100,  106,  145,  125,  146,  110,  107,  108,
      111,  114,  112,  109,  115,  113,  127,  134,  116,  126,
      128,  117,  131,  132,  129,  136,  118,  135,  138,  142,
      130,  147,  140,  148,  152,  139,  143,  133,   89,  137,
      141,  632,  153,  144,   68,  153,  154,  216,   90,  632,
      153,  632,  153,  632,  153,  632,  153,  632,  153,  156,
      217,  156,  632,  153,  632,  153,  632,  153,  632,  153,
      203,  632,  153,  632,  153,  105,  157,  632,  153,  629,

      161,  158,   85,   75,   87,  164,  173,  160,   77,  174,
       82,  162,   94,  101,   68,  104,   68,  189,  190,  225,
      628,  163,  100,  105,  226,  102,  165,  166,  192,  166,
      193,  204,  166,  166,  166,  166,  229,  166,  166,  166,
      257,  205,  166,  258,  166,  166,  627,  166,  166,  259,
      233,  230,  166,  239,  166,  166,  240,  234,  166,  235,
      261,  252,  166,  253,  264,  241,  242,  177,  185,  243,
      302,  244,   68,  153,  154,  632,  153,  632,  153,  632,
      153,  632,  153,  632,  153,  632,  153,  156,  632,  153,
      632,  153,  340,  263,  341,  265,  632,  153,  632,  153,

      183,  626,  266,  632,  153,  381,  303,  632,  153,  262,
      360,  632,  153,  197,  632,  153,  302,  382,  625,  267,
      632,  153,  632,  153,  472,  277,  632,  153,  271,  473,
      547,  362,  632,  153,  632,  153,  624,  363,  623,  622,
      548,  621,  549,  550,  620,  619,  437,  618,  364,  497,
      387,  617,  303,  616,  615,  614,  613,  612,  611,  610,
      609,  608,  607,  606,  605,  604,  603,  602,  513,   69,
       69,   69,   71,   71,  150,  150,  150,  155,  155,  168,
      168,  601,  600,  599,  598,  597,  596,  595,  594,  593,
      592,  591,  590,  589,  588,  587,  586,  585,  584,  583,

      582,  581,  580,  579,  578,  577,  576,  575,  574,  573,
      572,  571,  570,  569,  568,  567,  566,  565,  564,  563,
      562,  561,  560,  559,  558,  557,  556,  555,  554,  553,
      552,  551,  546,  545,  544,  543,  542,  541,  540,  539,
      538,  537,  536,  535,  534,  533,  532,  531,  530,  529,
      528,  527,  526,  525,  524,  523,  522,  521,  520,  519,
      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  507,  506,  505,  504,  503,  502,  501,  500,  499,
      498,  496,  495,  494,  493,  492,  491,  490,  489,  488,
      487,  486,  485,  484,  483,  482,  481,  480,  479,  478,

      477,  476,  475,  474,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,
      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  380,  379,  378,  377,  376,  375,  374,  373,

      372,  371,  370,  369,  368,  367,  366,  365,  364,  361,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  268,  151,

      260,  256,  255,  254,  251,  250,  249,  248,  247,  246,
      245,  238,  237,  236,  232,  231,  228,  227,  224,  223,
      222,  221,  220,  219,  218,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  191,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  172,
      171,  170,   73,  169,  167,   70,  159,  151,  149,  103,
       94,   93,   85,   80,   75,   74,   73,   73,   72,   70,
      632,    5,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632
    } ;

static yyconst short int yy_chk[846] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,   16,    7,    4,    7,   17,   19,
       17,   16,   19,   22,   31,   23,   35,   22,   20,   23,
       24,   35,   31,    2,    3,    3,    4,    3,   20,   23,
        3,    3,    3,    3,   24,    3,    3,    3,  628,    3,

        3,   36,    3,    3,   27,    3,    3,   29,   27,   37,
        3,   28,    3,    3,   36,  627,    3,   37,   27,   29,
        3,   28,   28,   32,   46,   38,   46,   33,   32,   32,
       33,   34,   33,   32,   34,   33,   39,   41,   34,   38,
       39,   34,   40,   40,   39,   42,   34,   41,   43,   45,
       39,   47,   44,   47,   50,   43,   45,   40,   50,   42,
       44,   53,   53,   45,   52,   52,   52,  117,   50,   54,
       54,   55,   55,   56,   56,   57,   57,   61,   61,   54,
      117,   55,   58,   58,   60,   60,   63,   63,   62,   62,
      105,   64,   64,   66,   66,  105,   56,   65,   65,  625,

       62,   58,   61,   57,   62,   66,   77,   60,   58,   77,
       60,   64,   63,   65,   68,  104,   68,   92,   92,  125,
      624,   64,   64,  104,  125,   65,   67,   67,   94,   67,
       94,  106,   67,   67,   67,   67,  128,   67,   67,   67,
      147,  106,   67,  147,   67,   67,  623,   67,   67,  147,
      131,  128,   67,  135,   67,   67,  135,  131,   67,  131,
      152,  143,   67,  143,  159,  135,  135,  159,  152,  135,
      203,  135,  154,  154,  154,  155,  155,  156,  156,  157,
      157,  158,  158,  160,  160,  161,  161,  156,  162,  162,
      163,  163,  242,  158,  242,  160,  164,  164,  262,  262,

      161,  621,  163,  263,  263,  289,  203,  265,  265,  157,
      262,  266,  266,  162,  267,  267,  302,  289,  620,  164,
      360,  360,  362,  362,  408,  265,  363,  363,  263,  408,
      510,  266,  437,  437,  497,  497,  619,  267,  616,  615,
      510,  614,  510,  510,  613,  612,  363,  609,  360,  437,
      362,  608,  302,  607,  606,  605,  604,  603,  602,  601,
      600,  598,  596,  595,  594,  593,  592,  591,  497,  633,
      633,  633,  634,  634,  635,  635,  635,  636,  636,  637,
      637,  590,  588,  587,  586,  581,  577,  576,  575,  574,
      573,  572,  571,  569,  565,  563,  562,  560,  559,  558,

      557,  556,  555,  554,  553,  551,  550,  549,  548,  547,
      546,  545,  540,  539,  537,  536,  535,  534,  532,  531,
      530,  526,  525,  524,  523,  521,  520,  519,  517,  516,
      514,  512,  509,  508,  505,  504,  503,  502,  501,  500,
      499,  498,  495,  494,  492,  491,  489,  487,  486,  483,
      482,  481,  480,  479,  478,  476,  475,  474,  473,  472,
      470,  468,  467,  462,  460,  459,  458,  457,  455,  452,
      451,  450,  449,  448,  446,  445,  444,  443,  442,  441,
      440,  436,  434,  433,  431,  430,  429,  427,  425,  424,
      423,  421,  420,  419,  418,  417,  416,  415,  414,  413,

      412,  411,  410,  409,  407,  405,  404,  403,  402,  401,
      399,  398,  397,  396,  394,  393,  390,  389,  388,  386,
      385,  384,  383,  382,  381,  379,  378,  377,  375,  374,
      373,  372,  370,  369,  368,  367,  366,  365,  361,  357,
      356,  355,  353,  352,  351,  350,  349,  348,  347,  346,
      344,  343,  342,  340,  339,  338,  337,  336,  335,  333,
      332,  331,  330,  329,  327,  326,  325,  324,  323,  322,
      318,  317,  316,  315,  314,  313,  311,  310,  309,  308,
      307,  306,  305,  304,  301,  299,  298,  297,  294,  293,
      292,  290,  288,  286,  285,  284,  283,  282,  281,  279,

      278,  277,  276,  275,  273,  272,  271,  270,  269,  264,
      261,  260,  259,  258,  257,  256,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  230,  229,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  150,

      149,  146,  145,  144,  142,  141,  140,  139,  138,  137,
      136,  134,  133,  132,  130,  129,  127,  126,  124,  123,
      122,  121,  120,  119,  118,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   93,   91,   90,   89,   88,   87,
       86,   85,   84,   83,   82,   81,   80,   79,   78,   76,
       75,   74,   73,   72,   71,   69,   59,   49,   48,   30,
       26,   25,   21,   18,   15,   14,   12,   11,   10,    9,
        5,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,

      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632,  632,  632,  632,  632,  632,
      632,  632,  632,  632,  632
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#define INITIAL 0
/*	SCCS Id: @(#)lev_lex.c	3.4	2000/12/22	*/
/*	Copyright (c) 1989 by Jean-Christophe Collet */
/* NetHack may be freely redistributed.  See license for details. */

#define LEV_LEX_C

#include "hack.h"
#include "lev_comp.h"
#include "sp_lev.h"

/* Most of these don't exist in flex, yywrap is macro and
 * yyunput is properly declared in flex.skel.
 */
#if !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
int FDECL(yyback, (int *,int));
int NDECL(yylook);
int NDECL(yyinput);
int NDECL(yywrap);
int NDECL(yylex);
	/* Traditional lexes let yyunput() and yyoutput() default to int;
	 * newer ones may declare them as void since they don't return
	 * values.  For even more fun, the lex supplied as part of the
	 * newer unbundled compiler for SunOS 4.x adds the void declarations
	 * (under __STDC__ or _cplusplus ifdefs -- otherwise they remain
	 * int) while the bundled lex and the one with the older unbundled
	 * compiler do not.  To detect this, we need help from outside --
	 * sys/unix/Makefile.utl.
	 *
	 * Digital UNIX is difficult and still has int in spite of all
	 * other signs.
	 */
# if defined(NeXT) || defined(SVR4) || defined(_AIX32)
#  define VOIDYYPUT
# endif
# if !defined(VOIDYYPUT) && defined(POSIX_TYPES)
#  if !defined(BOS) && !defined(HISX) && !defined(_M_UNIX) && !defined(VMS)
#   define VOIDYYPUT
#  endif
# endif
# if !defined(VOIDYYPUT) && defined(WEIRD_LEX)
#  if defined(SUNOS4) && defined(__STDC__) && (WEIRD_LEX > 1)
#   define VOIDYYPUT
#  endif
# endif
# if defined(VOIDYYPUT) && defined(__osf__)
#  undef VOIDYYPUT
# endif
# ifdef VOIDYYPUT
void FDECL(yyunput, (int));
void FDECL(yyoutput, (int));
# else
int FDECL(yyunput, (int));
int FDECL(yyoutput, (int));
# endif
#endif	/* !FLEX_SCANNER && !FLEXHACK_SCANNER */

#ifdef FLEX_SCANNER
#define YY_MALLOC_DECL \
	      genericptr_t FDECL(malloc, (size_t)); \
	      genericptr_t FDECL(realloc, (genericptr_t,size_t));
#endif

void FDECL(init_yyin, (FILE *));
void FDECL(init_yyout, (FILE *));

/*
 * This doesn't always get put in lev_comp.h
 * (esp. when using older versions of bison).
 */
extern YYSTYPE yylval;

int line_number = 1, colon_line_number = 1;
static char map[4096];
static int map_cnt = 0;

#define MAPC 1


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
extern int NDECL(yywrap);
#endif

#ifndef YY_NO_UNPUT
static void FDECL(yyunput, (int,char *));
#endif

#ifndef yytext_ptr
static void FDECL(yy_flex_strncpy, (char *,const char *,int));
#endif

#ifndef YY_NO_INPUT
static int NDECL(input);
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

int NDECL(yylex);
int yylex()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 633 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 782 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
		  BEGIN(INITIAL);
		  yylval.map = (char *) alloc(map_cnt + 1);
		  (void) strncpy(yylval.map, map, map_cnt);
		  yylval.map[map_cnt] = 0;
		  map_cnt = 0;
		  return MAP_ID;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
		  line_number++;
		  (void) strncpy(map + map_cnt, yytext, yyleng);
		  map_cnt += yyleng;
		  map[map_cnt] = 0;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
{ line_number++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ colon_line_number = line_number; return ':'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
return MESSAGE_ID;
	YY_BREAK
case 6:
YY_RULE_SETUP
return MAZE_ID;
	YY_BREAK
case 7:
YY_RULE_SETUP
return NOMAP_ID;
	YY_BREAK
case 8:
YY_RULE_SETUP
return LEVEL_ID;
	YY_BREAK
case 9:
YY_RULE_SETUP
return LEV_INIT_ID;
	YY_BREAK
case 10:
YY_RULE_SETUP
return FLAGS_ID;
	YY_BREAK
case 11:
YY_RULE_SETUP
return GEOMETRY_ID;
	YY_BREAK
case 12:
YY_RULE_SETUP
{ BEGIN(MAPC); line_number++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
return OBJECT_ID;
	YY_BREAK
case 14:
YY_RULE_SETUP
return COBJECT_ID;
	YY_BREAK
case 15:
YY_RULE_SETUP
return MONSTER_ID;
	YY_BREAK
case 16:
YY_RULE_SETUP
return TRAP_ID;
	YY_BREAK
case 17:
YY_RULE_SETUP
return DOOR_ID;
	YY_BREAK
case 18:
YY_RULE_SETUP
return DRAWBRIDGE_ID;
	YY_BREAK
case 19:
YY_RULE_SETUP
return MAZEWALK_ID;
	YY_BREAK
case 20:
YY_RULE_SETUP
return WALLIFY_ID;
	YY_BREAK
case 21:
YY_RULE_SETUP
return REGION_ID;
	YY_BREAK
case 22:
YY_RULE_SETUP
return RANDOM_OBJECTS_ID;
	YY_BREAK
case 23:
YY_RULE_SETUP
return RANDOM_MONSTERS_ID;
	YY_BREAK
case 24:
YY_RULE_SETUP
return RANDOM_PLACES_ID;
	YY_BREAK
case 25:
YY_RULE_SETUP
return ALTAR_ID;
	YY_BREAK
case 26:
YY_RULE_SETUP
return LADDER_ID;
	YY_BREAK
case 27:
YY_RULE_SETUP
return STAIR_ID;
	YY_BREAK
case 28:
YY_RULE_SETUP
return PORTAL_ID;
	YY_BREAK
case 29:
YY_RULE_SETUP
return TELEPRT_ID;
	YY_BREAK
case 30:
YY_RULE_SETUP
return BRANCH_ID;
	YY_BREAK
case 31:
YY_RULE_SETUP
return FOUNTAIN_ID;
	YY_BREAK
case 32:
YY_RULE_SETUP
return SINK_ID;
	YY_BREAK
case 33:
YY_RULE_SETUP
return POOL_ID;
	YY_BREAK
case 34:
YY_RULE_SETUP
return NON_DIGGABLE_ID;
	YY_BREAK
case 35:
YY_RULE_SETUP
return NON_PASSWALL_ID;
	YY_BREAK
case 36:
YY_RULE_SETUP
return ROOM_ID;
	YY_BREAK
case 37:
YY_RULE_SETUP
return SUBROOM_ID;
	YY_BREAK
case 38:
YY_RULE_SETUP
return RAND_CORRIDOR_ID;
	YY_BREAK
case 39:
YY_RULE_SETUP
return CORRIDOR_ID;
	YY_BREAK
case 40:
YY_RULE_SETUP
return GOLD_ID;
	YY_BREAK
case 41:
YY_RULE_SETUP
return ENGRAVING_ID;
	YY_BREAK
case 42:
YY_RULE_SETUP
return NAME_ID;
	YY_BREAK
case 43:
YY_RULE_SETUP
return CHANCE_ID;
	YY_BREAK
case 44:
YY_RULE_SETUP
return LEV;
	YY_BREAK
case 45:
YY_RULE_SETUP
{ yylval.i=D_ISOPEN; return DOOR_STATE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ yylval.i=D_CLOSED; return DOOR_STATE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
{ yylval.i=D_LOCKED; return DOOR_STATE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ yylval.i=D_NODOOR; return DOOR_STATE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ yylval.i=D_BROKEN; return DOOR_STATE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ yylval.i=W_NORTH; return DIRECTION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ yylval.i=W_EAST; return DIRECTION; }
	YY_BREAK
case 52:
YY_RULE_SETUP
{ yylval.i=W_SOUTH; return DIRECTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ yylval.i=W_WEST; return DIRECTION; }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ yylval.i = -1; return RANDOM_TYPE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
{ yylval.i = -2; return NONE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
return O_REGISTER;
	YY_BREAK
case 57:
YY_RULE_SETUP
return M_REGISTER;
	YY_BREAK
case 58:
YY_RULE_SETUP
return P_REGISTER;
	YY_BREAK
case 59:
YY_RULE_SETUP
return A_REGISTER;
	YY_BREAK
case 60:
YY_RULE_SETUP
{ yylval.i=1; return LEFT_OR_RIGHT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
{ yylval.i=2; return LEFT_OR_RIGHT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ yylval.i=3; return CENTER; }
	YY_BREAK
case 63:
YY_RULE_SETUP
{ yylval.i=4; return LEFT_OR_RIGHT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ yylval.i=5; return LEFT_OR_RIGHT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ yylval.i=1; return TOP_OR_BOT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ yylval.i=5; return TOP_OR_BOT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ yylval.i=1; return LIGHT_STATE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ yylval.i=0; return LIGHT_STATE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ yylval.i=0; return FILLING; }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ yylval.i=1; return FILLING; }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ yylval.i= AM_NONE; return ALIGNMENT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ yylval.i= AM_LAWFUL; return ALIGNMENT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ yylval.i= AM_NEUTRAL; return ALIGNMENT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ yylval.i= AM_CHAOTIC; return ALIGNMENT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ yylval.i= AM_SPLEV_CO; return ALIGNMENT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ yylval.i= AM_SPLEV_NONCO; return ALIGNMENT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ yylval.i=1; return MON_ATTITUDE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ yylval.i=0; return MON_ATTITUDE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ yylval.i=1; return MON_ALERTNESS; }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ yylval.i=0; return MON_ALERTNESS; }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ yylval.i= M_AP_FURNITURE; return MON_APPEARANCE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ yylval.i= M_AP_MONSTER;   return MON_APPEARANCE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ yylval.i= M_AP_OBJECT;    return MON_APPEARANCE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ yylval.i=2; return ALTAR_TYPE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ yylval.i=1; return ALTAR_TYPE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ yylval.i=0; return ALTAR_TYPE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ yylval.i=1; return UP_OR_DOWN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ yylval.i=0; return UP_OR_DOWN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ yylval.i=0; return BOOLEAN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
{ yylval.i=1; return BOOLEAN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ yylval.i=DUST; return ENGRAVING_TYPE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ yylval.i=ENGRAVE; return ENGRAVING_TYPE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ yylval.i=BURN; return ENGRAVING_TYPE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ yylval.i=MARK; return ENGRAVING_TYPE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ yylval.i=1; return CURSE_TYPE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ yylval.i=2; return CURSE_TYPE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
{ yylval.i=3; return CURSE_TYPE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
{ return CONTAINED; }
	YY_BREAK
case 99:
YY_RULE_SETUP
{ yylval.i=NOTELEPORT; return FLAG_TYPE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
{ yylval.i=HARDFLOOR; return FLAG_TYPE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
{ yylval.i=NOMMAP; return FLAG_TYPE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
{ yylval.i=ARBOREAL; return FLAG_TYPE; }	/* KMH */
	YY_BREAK
case 103:
YY_RULE_SETUP
{ yylval.i=SHORTSIGHTED; return FLAG_TYPE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
{ yylval.i = atoi(yytext + 1); return PERCENT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
{ yylval.i=atoi(yytext); return INTEGER; }
	YY_BREAK
case 106:
YY_RULE_SETUP
{ yytext[yyleng-1] = 0; /* Discard the trailing \" */
		  yylval.map = (char *) alloc(strlen(yytext+1)+1);
		  Strcpy(yylval.map, yytext+1); /* Discard the first \" */
		  return STRING; }
	YY_BREAK
case 107:
YY_RULE_SETUP
{ line_number++; }
	YY_BREAK
case 108:
YY_RULE_SETUP
;
	YY_BREAK
case 109:
YY_RULE_SETUP
{ yylval.i = yytext[2]; return CHAR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
{ yylval.i = yytext[1]; return CHAR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 112:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAPC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int old_size = b->yy_buf_size + 2;
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc2( (genericptr_t) b->yy_ch_buf,
							 b->yy_buf_size + 2, old_size );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 633 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 633 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 632);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


static int input()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					return input();
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


void yyrestart( input_file )
FILE *input_file;
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yy_delete_buffer( b )
YY_BUFFER_STATE b;
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (genericptr_t) b->yy_ch_buf );

	yy_flex_free( (genericptr_t) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int FDECL(isatty, (int));
#endif
#endif

void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#ifdef YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#ifdef YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


void yy_flush_buffer( b )
YY_BUFFER_STATE b;
	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}



#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error( msg )
const char msg[];
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
static void yy_flex_strncpy( s1, s2, n )
char *s1;
const char *s2;
int n;
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


static genericptr_t yy_flex_alloc( size )
yy_size_t size;
	{
	return (genericptr_t) alloc((unsigned)size);
	}

/* we want to avoid use of realloc(), so we require that caller supply the
   size of the old block of memory */
static genericptr_t yy_flex_realloc2( ptr, size, old_size )
genericptr_t ptr;
yy_size_t size;
int old_size;
	{
	genericptr_t outptr = yy_flex_alloc(size);

	if (ptr) {
	    char *p = (char *) outptr, *q = (char *) ptr;

	    while (--old_size >= 0) *p++ = *q++;
	    yy_flex_free(ptr);
	}
	return outptr;
	}

static void yy_flex_free( ptr )
genericptr_t ptr;
	{
	free( ptr );
	}

/*flexhack.skl*/

#ifdef	AMIGA
long *alloc(n)
	unsigned n;
{
	return ((long *)malloc (n));
}
#endif

/* routine to switch to another input file; needed for flex */
void init_yyin( input_f )
FILE *input_f;
{
#if defined(FLEX_SCANNER) || defined(FLEXHACK_SCANNER)
	if (yyin)
	    yyrestart(input_f);
	else
#endif
	    yyin = input_f;
}
/* analogous routine (for completeness) */
void init_yyout( output_f )
FILE *output_f;
{
	yyout = output_f;
}

/*lev_comp.l*/
