#	SCCS Id: @(#)Makefile.lib	3.4	1990/22/02
#	Nethack makefile for Fred fish termlib -- Norman Meluch
#
CC	= cl /c
MODEL	= L
CFLAGS	= /A$(MODEL) /Os /Oa /Gs /Zp1 /W0
#
# Termcap routines.
TERMLIB = termlib.lib
#
TL_LOBJECTS =	tgetent.o	tgetflag.o 	tgetnum.o	\
		tgetstr.o	tgoto.o		tputs.o		\
		isdigit.o	fgetlr.o
#
.SUFFIXES: .exe .o .c .obj .asm
#
.c.o:
	$(CC) $(CFLAGS) /Fo$*.o $*.c
#
$(TERMLIB):	$(TL_LOBJECTS)
	lib $(TERMLIB) -+ $(TL_LOBJECTS);
