/* NetHack 3.6	gn_xpms.h	$NHDT-Date: 1432512805 2015/05/25 00:13:25 $  $NHDT-Branch: master $:$NHDT-Revision: 1.9 $ */
/* Copyright (C) 1998 by Erik Andersen <andersee@debian.org> */
/* NetHack may be freely redistributed.  See license for details. */
/* These XPMs are the artwork of Warwick Allison
 * <warwick@troll.no>.  They have been borrowed from
 * the most excellent NetHackQt, until such time as
 * we can come up with something better.
 *
 * More information about NetHackQt can be had from:
 * http://www.troll.no/~warwick/nethack/
 */

/* clang-format off */
/* XPM */
static char *blind_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 5 1",
/* colors */
"  c #000000",
". c None",
"X c #909090",
"o c #606060",
"O c #303030",
/* pixels */
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"....ooooooooooooooooooooooooooooooooX...",
"....                                o...",
"....                                o...",
"....                                o...",
"....                                o...",
"......o            ..o            ......",
"......X           O..X           O......",
".......           o...           o......",
".......o          ....o          .......",
"........O        X.....O        X.......",
".........O      X.......O      X........",
"..........o   OX.........o   OX.........",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................",
"........................................"
};
/* XPM */
static char *cha_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 14 1",
/* colors */
"  c #F85848",
". c #949E9E",
"X c #F8B090",
"o c #E00028",
"O c #D4D4D4",
"+ c None",
"@ c #B0B0B0",
"# c #F82C24",
"$ c #F89E6C",
"% c #FF0000",
"& c #909090",
"* c #FFFFFF",
"= c #CEAA90",
"- c #DADAB6",
/* pixels */
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"+++++++++++++++=#%#=+=#%% ++++++++++++++",
"++++++++++++++ %O%%%#%$$%o%=++++++++++++",
"+++++++++++++# +#%%o%%o%%%%% +++++++++++",
"+++++++++++ %%%%%%%%%%%%%%%%o#=+++++++++",
"+++++++++ o%%%%%%%%%%%%%%%%%%%%# +++++++",
"++++++ #%%%%%%o%%%o%%o%%o%o%%%%%o%o  +++",
"++=#%%o%%%#= =*+**O*+**O*+- = =%%%%#@+++",
"++++ %=++*+*+**O****O****O*O*O*OO%=+++++",
"+++++.%=OO+*O*OO****+****+*O*+O&%=@+++++",
"++++++=%=*OO+**O**O*O**O*O*OO+$%=+++++++",
"+++++++#% +*OOOO****+****@O+*#%=++++++++",
"++++++++#%#*+**+O+OO+O+OOO*O#o#+++++++++",
"+++++++++o% O**+****O****O*#%%=+++++++++",
"+++++++++ %%#O*O****+****+ %o#++++++++++",
"++++++++++o%% XO*O**O*O**#%%%+++++++++++",
"++++++++++ %%%o%$-**+**$%%%%=+++++++++++",
"+++++++++++o%%$X$%%%%%%#= o#++++++++++++",
"++++++++++@ %%%o#O$$+$$$%%%=++++++++++++",
"++++++++++++#o%%%%%%%%o%%%=@++++++++++++",
"+++++++++++++ %%%%%%%%%%o=++++++++++++++",
"+++++++++++++++= &  &  @++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++"
};
/* XPM */
static char *chaotic_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 9 1",
/* colors */
"  c #000000",
". c #5C7A7A",
"X c None",
"o c #B0B0B0",
"O c #909090",
"+ c #788C8C",
"@ c #606060",
"# c #FFFFFF",
"$ c #303030",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXX@$     @XXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXX$$+#X$    $XXXXXXXXXX",
"XXXXXXXXXXXXXXXXXX@$#o        @XXXXXXXXX",
"XXXXXXXXXXXXXXXXXX$XX          OXXXXXXXX",
"XXXXXXXXXXXXXXXXX@ #   $@$     $XXXXXXXX",
"XXXXXXXXXXXXXXXXX@.+  $XXXO     @XXXXXXX",
"XXXXXXXXXXXXXXXXX O@  XXXXX@    @XXXXXXX",
"XXXXXXXXXXXXXXXXX @O $XXXXX@$   @XXXXXXX",
"XXXXXXXXXXXXXXXXX O+ @XXXXO++   @XXXXXXX",
"XXXXXXXXXXXXXXXXX @+ $@OXO$#$   XXXXXXXX",
"XXXXXXXXXXXXXXXXX O@  $ @$Xo   $XXXXXXXX",
"XXXXXXXXXXXXXXXXX +O  $X##+   $XXXXXXXXX",
"XXXXXXXXXXXXXXXXX +@         $XXXXXXXXXX",
"XXXXXXXXXXXXXXXXX oO        $XXXXXXXXXXX",
"XXXXXXXXO@@@@@   +#        $XXXXXXXXXXXX",
"XXXXXXO +o########$          $@XXXXXXXXX",
"XXXXXX                     +#+.$XXXXXXXX",
"XXXXXX                       @O @XXXXXXX",
"XXXXXX$        $@    $@@$       @XXXXXXX",
"XXXXXXX@@@@XXXXXX +  @XXXX@$    OXXXXXXX",
"XXXXXXXXXXXXXXXX@ #  @XXXXXXX@@OXXXXXXXX",
"XXXXXXXXXXXXXXXX@.+  @XXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXX$O@  XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXX @O  XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXX #$ @XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXX #  @XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXX #  @XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX@ #  @XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX@ #  OXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX@.X  XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX ++  XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX @+  XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX O@ @XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX +O @XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX    @XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX$   OXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXX@@OXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
/* XPM */
static char *cns_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 19 1",
/* colors */
"  c #000000",
". c #F85848",
"X c #949E9E",
"o c #F8B090",
"O c #E00028",
"+ c #7C3400",
"@ c None",
"# c #B0B0B0",
"$ c #F82C24",
"% c #F89E6C",
"& c #FF0000",
"* c #B64700",
"= c #909090",
"- c #788C8C",
"; c #606060",
": c #C80050",
"> c #CEAA90",
", c #303030",
"< c #FFB691",
/* pixels */
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@.oo.o$ ;@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@>.o.%%O,@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@$oo.o. ,@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@.oo$oo+ =@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@..o&oo$ ,@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@#.o.oo.  =@.$%@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@.o..oo& O.%ooo@@@@@@@@@@@@@",
"@@@@@@@@@@@@@.o.&%o.$oo%O++;@@@@@@@@@@@@",
"@@@@@@@@@@@@@.o.+$%$o<O+   ,@@@@@@@@@@@@",
"@@@@@@@@@@@@@.oo+ $o%O   ;@>.@@@@@@@@@@@",
"@@@@@@@@@@@@@.oo++o%$$ ,@@$.oo@@@@@@@@@@",
"@@@@@@@@@@@@>.oo+Oo$o%.@@$oo..-@@@@@@@@@",
"@@@@@@@@@@@@..o%;.o&%.$..o%O ++>@@@@@@@@",
"@@@@@@@@@@@@>.$O:%o.O::::O* $oooo@@@@@@@",
"@@@@@@@@@@@@::::::$$:OO&OO::oo%.;=@@@@@@",
"@@@@@@@@@@@.::::::::O&&&&&O::++  ,@@@@@@",
"@@@@@@@@@@>:::O&&OO&&&&&&&&::     ;@@@@@",
"@@@@@@@@@@=::O&&&&&O:O&&&&&O:  ,=@@@@@@@",
"@@@@@@@@@@:::&&&&&&&&:&&&&&O:  ;@@@@@@@@",
"@@@@@@@@@@::O&&&&&&&&:&O&&&O:, ;@@@@@@@@",
"@@@@@@@@@@::O&&&&O&O&OO&O&&O:+ ;@@@@@@@@",
"@@@@@@@@@@::&&&O&&&&&O:&&&&O:,  @@@@@@@@",
"@@@@@@@@@@::O&&&&&O&&&:O&O&::+  @@@@@@@@",
"@@@@@@@@@@::O&&O&&&&O&OO&&&::   @@@@@@@@",
"@@@@@@@@@@=::O&&&&O&&&O:&&&::   @@@@@@@@",
"@@@@@@@@@@.:::O&&O&&&&&:&OO::   @@@@@@@@",
"@@@@@@@@@@@:::::&&&&O&O:&&O:,   @@@@@@@@",
"@@@@@@@@@@.>:::::O&&&&&:&&::+  ;@@@@@@@@",
"@@@@@@@@@@>.<::::O&&O&O:&&::   @@@@@@@@@",
"@@@@@@@@@@@.o%,:::O&&&O:&O:,   @@@@@@@@@",
"@@@@@@@@@@@$o.  :::OO&OO&::,  ;@@@@@@@@@",
"@@@@@@@@@@@&o%+ ,::O&OO&O::   =@@@@@@@@@",
"@@@@@@@@@@@.oo+   :::OO:::   ,@@@@@@@@@@",
"@@@@@@@@@@@..oO    +:::::    =@@@@@@@@@@",
"@@@@@@@@@@@@.<.+      ,+,   ,@@@@@@@@@@@",
"@@@@@@@@@@@@Oo<+  @X,      ,@@@@@@@@@@@@",
"@@@@@@@@@@@@.%o$  @@@@@;, ;@@@@@@@@@@@@@",
"@@@@@@@@@@@@@.o., =@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
};
/* XPM */
static char *confused_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #303030",
"= c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOO.=.+OO=.+O.OO+O+OO.+OOOOOO",
"OOOOOOOOOOO++=====O=====+=O+==++=O+OOOOO",
"OOOOOOOOOOO+=.=====.=++++===OO==+O=+OOOO",
"OOOOOOOOOOO=+===.+=o==o===+&OoO======OOO",
"OOOOOOOO+O+====OO+=o&&&&Oo==o&oO+==+=.O.",
"OOOO+.+=+O==+&&o=oooOo&o&ooo=&oooO==O=+=",
"OOOOOOOO++O===oo=oo&=&o&&oo=o==&o+==++==",
"OOOOOOOO=o.=O====o&OO&o&oo&o&&oo=======O",
"OOOOOOOo===+=O=O=ooO=ooooOOo=o&O=====OOO",
"OOOOOOOOO+==+=======O=oo====O=o=O===+OOO",
"OOOOOOOOO.=#=X=+====O========O======OOOO",
"OOOOOOO.#Xo++.=#%====O==========OO==+OOO",
"OOOOOO+Xo#+#+.#=.==X====+====O=+=+==+OOO",
"OOOOO.+.+O===##.#=X.====oX##===o+OO.OOOO",
"OOOOO#+####O#O##o.#+==#X#O#+...=OOo=+OOO",
"OOOO++#o+#+X++++#.#O.#+#X.#+X+==+OO=oOOO",
"OOOO#+.+..X+.##X++#++#..+XX#+##+..OOOOOO",
"OOOO##....O+#++#+.++#+X+#+#X..+#+#OOOOOO",
"OOOO++#+.+.#+#O+X#X#XX#.++##.#++.X$OOOOO",
"OOOOO#+#+.+++#++.+++##+X###+X+X##+**OOOO",
"OOOOO#..#OO#+.##o###.+..++.+#X+#+#* @OOO",
"OOOOO+#.#O+#+#O.+++.###+##++###+.#* $OOO",
"OOOOOOXX+#+#+#o..X##++#+..##.#+###  *OOO",
"OOOOOOOX#.#X+#+#+#+.#+..+####%XX%%   OOO",
"OOOOOOOO.%%X.#+#+#.++#+#+#+.X++=.%  *OOO",
"OOOOOOOOO.* *##+#+.O####.+XX%%%%#%  $OOO",
"OOOOOOOOOOO.   %X.+.#+++XXX=.+++#X  $OOO",
"OOOOOOOOOOOO.*   %%X..#X%=.####%X*  $OOO",
"OOOOOOOOOOOOOO.$ *XX%%%=.#X%###=*   OOOO",
"OOOOOOOOOOOOOOOOOO+%%%=%%#.+.#=*   @OOOO",
"OOOOOOOOOOOOOOOOOOo=%%%==X##X%*    OOOOO",
"OOOOOOOOOOOOOOOOOOO+X%%%%X=%*     @OOOOO",
"OOOOOOOOOOOOOOOOOOOOX%%%%X      *@OOOOOO",
"OOOOOOOOOOOOOOOOOOOO=%%%X*   *$$OOOOOOOO",
"OOOOOOOOOOOOOOOOOOOO+X%%=  .OOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOX%%%  OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOO=%%* $OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOO=%%% $OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOO+%%% $OOOOOOOOOOOOO"
};
/* XPM */
static char *dex_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 19 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #F8B090",
"o c #5C7A7A",
"O c #D4D4D4",
"+ c #F87A24",
"@ c #7C3400",
"# c None",
"$ c #B0B0B0",
"% c #F89E6C",
"& c #B64700",
"* c #909090",
"= c #606060",
"- c #CEAA90",
"; c #DADAB6",
": c #303030",
"> c #F86800",
", c #FFB691",
"< c #F88C48",
/* pixels */
"########################################",
"########################################",
"########################################",
"########################################",
"########################################",
"########################################",
"###############-%-######################",
"##############-%X<-#####################",
"#########-<<-#-%XX+==###################",
"#########%,X< :<,X%@ :##################",
"#########-XX%: @;X%+  *#################",
"##########<,X& :<<%+: :#################",
"######->+#-%%%: <,XX@  #################",
"######%X%@ <,,& @XXX+  :++-#############",
"######-<X+ &,X%:@+<+>:  <X&o############",
"######$<X<@:<<%& <,XX@ @X,@ =###########",
"#######-+%< &,,%:&,XX+ @,X+ :###########",
"####<<-o&,X@:X,,&@,XX< @,X%& :##########",
"####<X%::%%< &,,X:<%X%@:%XX%@ =#########",
"####%%X& <X,&@%<%<%<<%& >+XX+  #########",
"#####+%%@@,X%<,XXXXXXX<:@XXX<: =########",
"####$%XX< <,<XXXXXXXXXX&@,XXX@ :########",
"######+X<&@%%XXX%XXXX%<<><,XX&  ########",
"#####$%<%X@%XXXX<X%XXXX<><%XX<  =#######",
"#######<;X%XXXXX<<<XXX<XX<,XX%@ =#######",
"#######-%+XXXXX%+XXXXXXXX%<,XX@ =#######",
"########<XXXXXX+XX%XXXXXXXX%XX@ =#######",
"########-%XXX%+%XX<XXXXXXXX%XX@  #######",
"#########+,XX+XXXX<,XXXXXXXXXX@  #######",
"#########-<X+%XXXX%,XXXXXXXXXX@  #######",
"##########>,XXXXXX%,XXXXXXXXX%@  #######",
"##########-<XXXXXX<,XXXXXXXXX<   #######",
"###########%%XXXXXX%,,XXXXXXX+   #######",
"############+,XXXXXX<;,,XXXXX@   #######",
"############-+,XXXXXX%%%,XXX%@   #######",
"#############%%XXXXXXXX%<XXXX+  =#######",
"#############$%<XXXXXXXXXXXXX<: =#######",
"##############$-<<XXXXXXXXXXXX&  #######",
"################.&,XXXXXXXXXXX<: =######",
"#################O######################"
};
/* XPM */
static char *ext_enc_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #303030",
"= c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOoO+OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOoOXX==OOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoO=OO+==OOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoXOO.*$=$OOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO=+# *.X *OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO==.OO=+@ $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOXO==.OO $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOO+=@$@* @OOOOOOOOOOOOOO",
"OOOOOOOOOOO&&&&&&&&&&&&&&&.OOOOOOOOOOOOO",
"OOOOOOOOOOOo==============X*OOOOOOOOOOOO",
"OOOOOOOOOOoO===X====X=====X**OOOOOOOOOOO",
"OOOOOOOOOO&============X===% $OOOOOOOOOO",
"OOOOOOOOOoo======X=========%* OOOOOOOOOO",
"OOOOOOOOOoO===X============X* @OOOOOOOOO",
"OOOOOOOOO&=========X===%%===% $OOOOOOOOO",
"OOOOOOOOoo===     ===%   *==X  OOOOOOOOO",
"OOOOOOOOoO==* %*%*=== *%* *=X* @OOOOOOOO",
"OOOOOOOO&=== %======% ===% ==% $OOOOOOOO",
"OOOOOOOoo==* ======= *===% X=%* OOOOOOOO",
"OOOOOOOoO==%    *%== *==== %=X* @OOOOOOO",
"OOOOOOO&===%%*%*  == %==== *==% $OOOOOOO",
"OOOOOOoo========% %=* ===X X==X  OOOOOOO",
"OOOOOOoO===*====* *=% ===* ===X* @OOOOOO",
"OOOOOO&===*  %*%  X== **% %====% $OOOOOO",
"OOOOOoo===%%    *X===%   *=====%* OOOOOO",
"OOOOOo+========================X* @OOOOO",
"OOOOOo=========================%* $OOOOO",
"OOOOOO=XXX%X%XXXXX%X%XXXX%X%X%X%*  OOOOO",
"OOOOOO.=************************   OOOOO",
"OOOOOOOO                           OOOOO",
"OOOOOOOO.                         @OOOOO",
"OOOOOOOOOOoOOoOOoOOoOoOoOOoOoOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *hallu_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 30 1",
/* colors */
"  c #F85848",
". c #5C7A7A",
"X c #009100",
"o c #6CFF00",
"O c #E00028",
"+ c #D4D4D4",
"@ c #FF6C00",
"# c #F87A24",
"$ c None",
"% c #B0B0B0",
"& c #F82C24",
"* c #F89E6C",
"= c #FF00FF",
"- c #FF0000",
"; c #B64700",
": c #909090",
"> c #788C8C",
", c #606060",
"< c #406868",
"1 c #C80050",
"2 c #FFFFFF",
"3 c #FFFF00",
"4 c #00B6FF",
"5 c #CEAA90",
"6 c #DADAB6",
"7 c #F86800",
"8 c #FFB691",
"9 c #6C91B6",
"0 c #F88C48",
"q c #0000FF",
/* pixels */
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
"$$$$$$$$$$$$$$$353333335*$$$$$$$$$$$$$$$",
"$$$$$$$$$$$$*33333333#7@3335$$$$$$$$$$$$",
"$$$$$$$$$65333333333@7777#333*$$$$$$$$$$",
"$$$$$$$$$3333333333377777733333===%$$$$$",
"$$$$$$$533333333333#7777777333%=====$$$$",
"$$$$$$ #3333333333o>7777773330======%$$$",
"$$$$5---O#33333o3944077777333*=======$$$",
"$$$$-----O333333>4444.77333330======%$$$",
"$$$ ---O--;3333344444443333333:====5$$$$",
"$$$ O-----733333444444433333333 ==035$$$",
"$$$3--O--O333333>44444>33333333333333$$$",
"$$533---O33333333944493333#333333333356$",
"$$33867733333o33333:o333333o3333333333$$",
"$532+2233333#333333333333oooo3#3333333%$",
"6522222+33333333333333333oooooo33o3333*$",
"$+22+22263333333o3333333ooooooo333333356",
"662222+2533333333333333#ooooooo33333333$",
"$32+22223333o3#33333o333ooooooo3#333333%",
"$33222233333333333#333333ooooo333333333$",
"$33368333333333333330626*oooo#333333o33%",
"%333335== 33oo333333222223#333333333333$",
"$3333=====:ooooo333+22+2263333333.>o333%",
"$5333=====oooooo33322222223333339444935$",
"$*33 ====>ooooooo3362+222633333.44444>3$",
"$%330====:ooooooo333222+23333334444444$$",
"$$333177 =oooXoo#333*626333333;4444444$$",
"$$53##777&3oooo3333333333333#--,444449$$",
"$$$3;77777#3o333333333333333O---94449$$$",
"$$%*@77777#33333333333333337O----O:o3$$$",
"$$$5777777333  333333333333;---O-O73$$$$",
"$$$$#7777730====#:.,33333333------3$$$$$",
"$$$$$577333=====qqqq<0333333#O---35$$$$$",
"$$$$$%53335====qqqqqq.33o333337735$$$$$$",
"$$$$$$$533 ====qqqqqqq3333333333%$$$$$$$",
"$$$$$$$$%33====qqqqqqq333333333%$$$$$$$$",
"$$$$$$$$$$50===qqqqqq,3333333:$$$$$$$$$$",
"$$$$$$$$$%6%5503,qqq<333#335%$$$$$$$$$$$",
"$$$$$$$$$$$$$%$*53,03335o$%%$$$$$$$$$$$$",
"$$$$$$$$$$$$$$$$$$$$$%$$+$$$$$$$$$$$$$$$"
};
/* XPM */
static char *hungry_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 15 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #CEAA90",
"= c #DADAB6",
"- c #303030",
"; c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO========OOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOO=============OOOOOOOOOOOOO",
"OO;XX;@OOOOO================OOOOOOOO;XOO",
"OO;%-;$OOOO==================OOOOOOO;XOO",
"OO;-%;$OOO========@$#@========OOOOO+;;$O",
"OO;%-;$OO=======-     -*======*OOOO.;;$O",
"OO;-%;$O======*  @====.$$&=====@OOO.;;$O",
"OO;X%;$O====== -========*@=====*.OO+;;$O",
"OO;;;X$o====* -==========@======$OO;;;$O",
"OO+;;-+o====- =============o====#@O+;;$O",
"OOO;%$O===== @=============&====*$O;;;$O",
"OOO+%OO====@ ==============&=====-OO;;$O",
"OOo;-Oo====$ ==============o&==== OO;;$O",
"OOO+%OO====@ ==============&===== O+;;#O",
"OOO;-Oo====$-==============&&==== O+;;-O",
"OOO;;+O=====$*============&&====* OO;;%+",
"OOO;;$o=====$.============&&====X-OO;;$O",
"OOO;;$O======*.===&======&&=====-$=O;;$O",
"OOO;;$Oo=====.==========&&=====* @O+;;$O",
"OOO;;$OO=======oo=====&&&======$-OOO;;$O",
"OOO;;$OOo=======&o&&&&&&======$ @OOO;;$O",
"OOO;;$OOOO========&=&========* $OOOO;;$O",
"OO+;;$OOOOo=================* -OOOOO#;$O",
"OOO;;$OOOOO=*==============@ -=OOOOO;;$O",
"OOO;;$OOOOOOO+*==========*- $OOOOOOO;;$O",
"OOOX-$OOOOOOOO@X@*====*#- -.OOOOOOOOX-$O",
"OOOOOOOOOOOOOO=*@$-    -$.=OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOO=O==O=O=OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *hvy_enc_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #303030",
"= c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOoO+OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOoOXX==OOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoO=OO+==OOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoXOO.*$=$OOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO=+# *.X *OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO==.OO=+@ $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOXO==.OO $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOO+=@$@* @OOOOOOOOOOOOOO",
"OOOOOOOOOOO&&&&&&&&&&&&&&&.OOOOOOOOOOOOO",
"OOOOOOOOOOOo==============X*OOOOOOOOOOOO",
"OOOOOOOOOOoO===X====X=====X**OOOOOOOOOOO",
"OOOOOOOOOO&============X===% $OOOOOOOOOO",
"OOOOOOOOOoo===*%====***%===%* OOOOOOOOOO",
"OOOOOOOOOoO==% %===*    %==X* @OOOOOOOOO",
"OOOOOOOOO&===% *==% X==**===% $OOOOOOOOO",
"OOOOOOOOoo===% %==% ===% ===X  OOOOOOOOO",
"OOOOOOOOoO==== *== *==== *==X* @OOOOOOOO",
"OOOOOOOO&===== %== %==== %===% $OOOOOOOO",
"OOOOOOOoo===== *== *==== *===%* OOOOOOOO",
"OOOOOOOoO===== %==% ===* ====X* @OOOOOOO",
"OOOOOOO&===X== *==% X==**=====% $OOOOOOO",
"OOOOOOoo=====   *==*    %=====X  OOOOOOO",
"OOOOOOoO=====*%%X===*%*X======%* @OOOOOO",
"OOOOOOo====================X===* $OOOOOO",
"OOOOOOO=%X%XXXX%XXXXXXXXX%X=%X%   OOOOOO",
"OOOOOOO.=**********************   OOOOOO",
"OOOOOOOOO                         OOOOOO",
"OOOOOOOOO.                       @OOOOOO",
"OOOOOOOOOOOoOOoOoOoOoOoOoOOoOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *int_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 12 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #303030",
"* c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOO+#.X.##@#OOOOOOOOOOOOOOOOOO",
"OOOOOOOO+##@X#O++.#+#.##OOOOOOOOOOOOOOOO",
"OOOOOO+#Xo++#X#%#+##o#O#.#+OOOOOOOOOOOOO",
"OOOOO.Xo#+#++##+.XX#..+.+..XOOOOOOOOOOOO",
"OOOO++.+O.+O##+#.X###..OX#.+X+OOOOOOOOOO",
"OOOO#+####O#O##o##+###X#+#+.#..OOOOOOOOO",
"OOO.+#o+#+X++++#.#O+#+#X.#+X++X+OOOOOOOO",
"OOO.+.+..X+.##X++#++#..+XX#+#X+..OOOOOOO",
"OOO##....O+#++#+.++#+X+#+#X..+#+#OOOOOOO",
"OOO++#+.+.#+#O+X#X#XX#.++##.#++.X$OOOOOO",
"OOOO#+#+.+++#++.+++##+X###+X+X##+&&OOOOO",
"OOOO#..#OO#+.##o###.+..++.+#X+#+#& @OOOO",
"OOOO.#.#O+#+#O.+++.###+##++###+.#  $OOOO",
"OOOOOXX+#+#+#o..X##++#+..##.#+###  &OOOO",
"OOOOOOX#.#X+#+#+#+.#+..+####XX%X%   OOOO",
"OOOOOOO.%%X.#+#+#.++#+#+#+.%++*+%  &OOOO",
"OOOOOOOO@& &##+#+.O####.+XXX%%%#%  $OOOO",
"OOOOOOOOOO.   %X.+.#+++XXX*.+++#%  $OOOO",
"OOOOOOOOOOO@&   %%X..#XXX.####%%&  $OOOO",
"OOOOOOOOOOOOO@$ &XX%%%*.#X%###*&   OOOOO",
"OOOOOOOOOOOOOOOOO+%%%*%%#.+.#*&   @OOOOO",
"OOOOOOOOOOOOOOOOOO*%%%*.X##XX&    OOOOOO",
"OOOOOOOOOOOOOOOOOOOX%%%%X*%&     @OOOOOO",
"OOOOOOOOOOOOOOOOOOOX%%%%%      &@OOOOOOO",
"OOOOOOOOOOOOOOOOOOO*%%%X&   &$$OOOOOOOOO",
"OOOOOOOOOOOOOOOOOOO+%%%*  .OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOO+*%%%  OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOO*%%& $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOO*%%% $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOO+%%& $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOoOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *lawful_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 10 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #606060",
"$ c #FFFFFF",
"% c #303030",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOo$$$$$$oOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOO$$o$$o$$$$$OOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOo$$$$$$$o$$ooOOOOOOOOO",
"OOOOOOOOOOOOOOOOOO$o$$$o$$$$$$$oOOOOOOOO",
"OOOOOOOOOOOOOOOOOo$$$$+ .o$$$$$oOOOOOOOO",
"OOOOOOOOOOOOOOOOOo$$$+%OOOO$o$$$oOOOOOOO",
"OOOOOOOOOOOOOOOOO$$o$X@OOOOo$$$ooOOOOOOO",
"OOOOOOOOOOOOOOOOO$$$$%OOOOOo$$$..OOOOOOO",
"OOOOOOOOOOOOOOOOO$$$$@OOOOo$$oo##OOOOOOO",
"OOOOOOOOOOOOOOOO+$$o$$ooOoo$$$o OOOOOOOO",
"OOOOOOOOOOOOOOOOO$$$$$$$o$$$$o#%OOOOOOOO",
"OOOOOOOOOOOOOOOO+$$o$$o$$$$$o@%OOOOOOOOO",
"OOOOOOOOOOOOOOOOO$$$$$$$$o$o.%OOOOOOOOOO",
"OOOOOOOOOOOOOOOOOo$$$o$$oo@#%OOOOOOOOOOO",
"OOOOOOOOoooooo$$$$$$$$$$$% %OOOOOOOOOOOO",
"OOOOOOO$$$$$$$$$$$$o$$o$$$$$$$oOOOOOOOOO",
"OOOOOO$$$$$$$$$o$$$$$$$$$$$$o$$oOOOOOOOO",
"OOOOOO$$o$ooooo##+o$$+##@oo$$$$$oOOOOOOO",
"OOOOOOo$$#%    %#$$$+%##%%#ooo$O#OOOOOOO",
"OOOOOOOo@##OOOOO+$$$##OOOO#%%##%@OOOOOOO",
"OOOOOOOOOOOOOOOOo$$$##OOOOOOO##@OOOOOOOO",
"OOOOOOOOOOOOOOOOo$$o##OOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO$$oo OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO+$$$o OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO$$$##OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO$o$##OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO$$$##OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo$$$##OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo$$o%@OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo$$o OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO$$oo OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO$$$o OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO$$$##OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo$$##OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO$$o##OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo$# @OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO.#@OOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *mod_enc_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #303030",
"= c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOoO+OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOoOXX==OOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoO=OO+==OOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoXOO.*$=$OOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO=+# *.X *OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO==.OO=+@ $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOXO==.OO $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOO+=@$@* @OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOo&&&&&&&&&oXOOOOOOOOOOOOOOO",
"OOOOOOOOOOOO+&=========X%@OOOOOOOOOOOOOO",
"OOOOOOOOOOOOO&=====X====% @OOOOOOOOOOOOO",
"OOOOOOOOOOOOoO==X=======X* OOOOOOOOOOOOO",
"OOOOOOOOOOOO&====*%*%*===* $OOOOOOOOOOOO",
"OOOOOOOOOOO+&===X     ===% *OOOOOOOOOOOO",
"OOOOOOOOOOOoO===**=======X* OOOOOOOOOOOO",
"OOOOOOOOOOO&===% %=======X% $OOOOOOOOOOO",
"OOOOOOOOOOO&===% %*%%=====% *OOOOOOOOOOO",
"OOOOOOOOOOoO===*      ====X* OOOOOOOOOOO",
"OOOOOOOOOO&=========* X===X% $OOOOOOOOOO",
"OOOOOOOOO+&=========% *====% *OOOOOOOOOO",
"OOOOOOOOOoO===% %===  %====%* OOOOOOOOOO",
"OOOOOOOOO&====*      *==X===% $OOOOOOOOO",
"OOOOOOOOO&======*%*%X=======% *OOOOOOOOO",
"OOOOOOOOOo==X===============%  OOOOOOOOO",
"OOOOOOOOO=XXXXXXXXXX%X%X%X%%%  $OOOOOOOO",
"OOOOOOOOOO=%****************   $OOOOOOOO",
"OOOOOOOOOOO$                   $OOOOOOOO",
"OOOOOOOOOOOO*                 *OOOOOOOOO",
"OOOOOOOOOOOOOoOOoOoOoOoOoOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *neutral_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 14 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #00B6FF",
"= c #303030",
"- c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOO.------.OOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOO-+O&o.-----OOOOOOOOOO",
"OOOOOOOOOOOOOOOOOO+-&o--------.OOOOOOOOO",
"OOOOOOOOOOOOOOOOOO-oo----------+OOOOOOOO",
"OOOOOOOOOOOOOOOOO+-&--% #-------OOOOOOOO",
"OOOOOOOOOOOOOOOOO-OO-X=OOO.-----+OOOOOOO",
"OOOOOOOOOOOOOOOOO-oO-%#OOOO.-----OOOOOOO",
"OOOOOOOOOOOOOOOOO--O-=OOOOO+---X#OOOOOOO",
"OOOOOOOOOOOOOOOOO-oO-XOOOO+OO--=$OOOOOOO",
"OOOOOOOOOOOOOOOOO-OO--++OO-&--- OOOOOOOO",
"OOOOOOOOOOOOOOOOO-OO-----+oo--%=OOOOOOOO",
"OOOOOOOOOOOOOOOOO--O--+o&&o--%=OOOOOOOOO",
"OOOOOOOOOOOOOOOOO-oo*-------%=OOOOOOOOOO",
"OOOOOOOOOOOOOOOOO-oO------%%=OOOOOOOOOOO",
"OOOOOOOO+.+-+.---O&------= =OOOOOOOOOOOO",
"OOOOOO+-oo&&&&&&&&------------.OOOOOOOOO",
"OOOOOO---------------X-----O&Oo-OOOOOOOO",
"OOOOOO---------%=%---%%=%----OO-.OOOOOOO",
"OOOOOO---==    =%---%=%%===----%XOOOOOOO",
"OOOOOOO-#$%OOOOOO-+-%$OOOO%===%=@OOOOOOO",
"OOOOOOOOOOOOOOOO.-&-=%OOOOOOO%%#OOOOOOOO",
"OOOOOOOOOOOOOOOo-O+-%$OOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO-oO- OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO-OO- OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO-&-%%OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO-&-%$OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO-&-=$OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO--o-%$OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO+-&- .OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO-Oo- OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO-OO- OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO-oO- OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO-OO%%OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO-o-%$OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO---%$OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO--% #OOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOX$@OOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *ovr_enc_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #303030",
"= c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOoO+=+OOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOo=#===+OOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo=.OO@X=OOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo#OO* #X @OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO+=.XX+=#* @OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO+=O=.=OO $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOO#.=+OO@ $OOOOOOOOOOOOOO",
"OOOOOOOOOooooooooo&O.#+#XooooOOOOOOOOOOO",
"OOOOOOOOO&OOoOoOoOOOOOOOOOoO%@OOOOOOOOOO",
"OOOOOOOOoO==================X*@OOOOOOOOO",
"OOOOOOOO&===================X% @OOOOOOOO",
"OOOOOOOO&==%*%*%*%*%*%*%*%*==% *OOOOOOOO",
"OOOOOOOoO==%*%%*%%*%%*%*%*%==X* OOOOOOOO",
"OOOOOOO&======================* $OOOOOOO",
"OOOOOO+&===                ===% *OOOOOOO",
"OOOOOOoO======================X* OOOOOOO",
"OOOOOO&=======================X% $OOOOOO",
"OOOOOOo========================% *OOOOOO",
"OOOOOoO===*%X=====%%======%%===X* OOOOOO",
"OOOOO&==%    %==%   *====    %==* $OOOOO",
"OOOOO&== *==**== **% *=X% %%* ==% *OOOOO",
"OOOOoO==%%==* =* ===% == %=== %=X* OOOOO",
"OOOO&=======% =**===% %X %X==* =X% $OOOO",
"OOOO&======% %= %==== %% ====* ==% *OOOO",
"OOOoO=====% *== *==== %* ====% ==X* OOOO",
"OOO&====XX *===**===% X% X=== *===* $OOO",
"OO+&====X *====* ===% == *=== %===% *OOO",
"OOoO===%  %*%*== *** %==% %** ====X* OOO",
"OO&====%      ==X   *====*   %====X% $OO",
"OO&================================% *OO",
"OOo===X============================%  OO",
"OO=XXXXXXXXXXXX%XXXX%X%X%XXXXX%X%X%%  $O",
"OOO=%******************************   $O",
"OOOO$                                 $O",
"OOOOO*                               *OO",
"OOOOOOOOOOoOOoOOoOOoOOoOOoOOoOOoOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *satiated_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 23 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #F8B090",
"o c #5C7A7A",
"O c #D4D4D4",
"+ c #F87A24",
"@ c #7C3400",
"# c None",
"$ c #B0B0B0",
"% c #F89E6C",
"& c #914700",
"* c #B64700",
"= c #909090",
"- c #788C8C",
"; c #606060",
": c #406868",
"> c #FFFFFF",
", c #CEAA90",
"< c #DADAB6",
"1 c #303030",
"2 c #FFB691",
"3 c #6C91B6",
"4 c #F88C48",
/* pixels */
"########################################",
"########################################",
"########################################",
"########################################",
"########################################",
"########################################",
"########################################",
"################<<<<<<<<################",
"##############<<<<<<<<<<$#$$$###########",
"############<<<<<<<<<<$:31:3:###########",
"###########<<<<<<%42<<#:3:133-##########",
"##########<<<<<%<<;;=o$131:33;##########",
"#########<<<<<<,1     ::31:33;,#########",
"########<<<<<<,  =<<<<.13:133;<=########",
"########<<<%2, 1<<<<<<#333:33;<,=#######",
"#######<<<<X$ 1<<422<<<33313--<<;#######",
"#######<<<<<1 <<<<<%<<<#31333;<<-=######",
"#######<<<<< -<<+%,%<<%<31.3-;<<,;######",
"#######<<<2- <<<+&<%<2+<3o<33o<<<1######",
"######O<<<%; <<<&,4=4%<<-o<3-=<<< ######",
"#######<<<%; <2+4,&*,,,<3o<33o<<< ######",
"######<<<<<-1<<<<,4<4<<<.;<3-1<<< ######",
"#######<<<<<;,<<4,,4X<<#3-<33o<<, ######",
"######O<<<<<;.<<<,&%<2<$3:>3-=<<o1######",
"#######<<<<<<=,<<<<<<4<#31>33;<<@o######",
"#######O<<<<<,#<<<<<<<<.3:<3-;<, =######",
"########<<<<2<<<<<<<<<>#31<33o<11#######",
"########O<<<<44<>O>>>>>#3:<3.;- =#######",
"##########<<<4<<<<><><<$3:<331 ;<#######",
"##########<<<<<<<%2<<<<$3:<33 1#########",
"###########O,<<<<<<<<<<#31<331##########",
"#############.<<<<<<<<<$3:133;##########",
"##############=;=,<<<<,o  1;;=##########",
"###############<=;1    1;=##############",
"#################<#<O#<#################",
"########################################",
"########################################",
"########################################",
"########################################",
"########################################"
};
/* XPM */
static char *sick_fp_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 30 1",
/* colors */
"  c #F85848",
". c #949E9E",
"X c #F8B090",
"o c #5C7A7A",
"O c #009100",
"+ c #6CFF00",
"@ c #E00028",
"# c #D4D4D4",
"$ c #FF6C00",
"% c #F87A24",
"& c #7C3400",
"* c None",
"= c #B0B0B0",
"- c #F89E6C",
"; c #FF0000",
": c #914700",
"> c #B64700",
", c #909090",
"< c #788C8C",
"1 c #606060",
"2 c #406868",
"3 c #FFFFFF",
"4 c #CEAA90",
"5 c #DADAB6",
"6 c #303030",
"7 c #F86800",
"8 c #FFB691",
"9 c #6C91B6",
"0 c #F88C48",
"q c #0000FF",
/* pixels */
"****************************************",
"*************#333333333#****************",
"***********##33333#333333#**************",
"**********#33333#33333#33*==************",
"*********#33##33-;-3#3333399************",
"********#33#33#3-@ 33333#33=.***********",
"********#3*#33-;;;;;-33333#99***********",
"*******#3*3333-;;;;@ 33#333#9=**********",
"*******#333#33#3-;-33#*##33399**********",
"******#3#3333333-@-#333#9933*9=*********",
"******#333#33#3333333#333*9999=*********",
"******#333333333#3#33333333*999*********",
"******#3#33#33333333#33#3333#9=*********",
"******#333334>&&:&&>::44,3#33#9*********",
"******#33*::&41OOO6:4O 0::4433=*********",
"******#3:>,0:O0O1O+O:O<O4-:-:1#*********",
"******#0&>XO,O+2+OOo4<+1104:>:#*********",
"******.&:1OOO,14X2O48:O80,440:,*********",
"******4::>OOO%8-X4O4%O,84+O0X&>=********",
"******.::>,O 99*X+<$,+.o*1O4&0:*********",
"******>:0&4O5qq9#10OO3qq9,+X:1:*********",
"****=>,,::,O4qq9X+O>O-qq9O2X0,>*********",
"******4:>OOOO48882OOOO+4OOO07*4*********",
"******4*,4OO+OXX3O<OOOOOOOO:-***********",
"********0><OO1+O,+1+2OOOOOO%4=**********",
"********47+OO1O12O:<14OO1OO7=***********",
"*********-11OO+,+<1004OOOO:-************",
"**********:OOOOOO-+,4O+OOO%4************",
"**********04O4O,-OOOOO<OOO>5************",
"*********=0%,OO,>:>>O +1OO4*************",
"**********=%+OO:::1:::6+:7**************",
"***********7&OO:O+O,O1OO+1**************",
"***********40OO,O4:OOO11O<5*************",
"**********=4 +O1O2+O2+O0O***************",
"************72O+1+21-OOO%5**************",
"************0%1OOOO+O+174***************",
"*************%%O,OO1407-=***************",
"**************-$>%0%:74*****************",
"****************54044*=*****************",
"*****************=*=********************"
};
/* XPM */
static char *sick_il_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 23 1",
/* colors */
"  c #F85848",
". c #949E9E",
"X c #F8B090",
"o c #E00028",
"O c #D4D4D4",
"+ c #F87A24",
"@ c #7C3400",
"# c None",
"$ c #B0B0B0",
"% c #F89E6C",
"& c #FF0000",
"* c #914700",
"= c #B64700",
"- c #909090",
"; c #606060",
": c #FFFFFF",
"> c #CEAA90",
", c #DADAB6",
"< c #F86800",
"1 c #FFB691",
"2 c #6C91B6",
"3 c #F88C48",
"4 c #0000FF",
/* pixels */
"########################################",
"#############O:::::::::O################",
"###########OO:::::O::::::O##############",
"##########O:::::O:::::O::#$$############",
"#########O::OO::%&%:O:::::22############",
"########O::O::O:%o :::::O::$.###########",
"########O:#O::%&&&&&%:::::O22###########",
"#######O:#::::%&&&&o ::O:::O2$##########",
"#######O:::O::O:%&%::O#OO:::22##########",
"######O:O:::::::%o%O:::O22::#2$#########",
"######O:::O::O:::::::O:::#2222$#########",
"######O:::::::::O:O::::::::#222#########",
"######O:O::O::::::::O::O::::O2$#########",
"######O:::::>=@@=**=**>>-:O::O2#########",
"######O::#**@3>%* ;=>=3;<@>>::$#########",
"######O:** >=>XXXX1X >>+>%*%*;O#########",
"######O3@*,X%XXXXXXX>X%XX >*=*O#########",
"######.@@3XXXXXXXXXXXXXXX>X>3*-#########",
"######>***>X% >XXXXX3XXXXXX%>*=>########",
"######.***>  22#XXX<%X22#XXX@+;#########",
"######=*3@X>O442OXX<X:442OXX=;=#########",
"####$=--;=X1,442XXX<X1442XXX3-*#########",
"######>==%XX11111O1+%X111XX%<#>#########",
"######.,;XXXXXX1O1X%3XXXXX%+3###########",
"########3=XXXXXX:XXXXXXXXX+<>$##########",
"########>+XXXXXX%-3->XXXX%+<############",
"#########%3XXXXXX>- -%XXX%<%$###########",
"#########$<XXXXXX%X%XXXX%3<>############",
"##########+%XXXXXXXXXXXX%+<#############",
"##########%3XXX>=****3XX%<%#############",
"##########>+XXX**=3-*@3>3+##############",
"###########<%XX >XX%X;%X3+##############",
"###########%3XX>XX++XXXX<%$#############",
"##########$>+XXXXXXXXXXX<###############",
"############<%XXXXXXXXX3+###############",
"###########$%+XXXXXXXX%<>###############",
"#############++XXXXXX%<%$###############",
"#############$%<<3333<%#################",
"#################%3>>$##################",
"#################$#$####################"
};
/* XPM */
static char *slt_enc_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #FFFFFF",
"* c #303030",
"= c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOoO+OOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOoOXX==OOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoO=OO+==OOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOoXOO.*$=$OOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO=+# *.X *OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOO==.OO=+@ $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOXO==.OO $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOO+=@$@* @OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOO&&&&&&&X @OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOo======X*OOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOoO======X**OOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOO&====X===% $OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOoo==%* %==%* OOOOOOOOOOOOOO",
"OOOOOOOOOOOOOoO=%  %  =X* @OOOOOOOOOOOOO",
"OOOOOOOOOOOOO&==**==% %=% $OOOOOOOOOOOOO",
"OOOOOOOOOOOOoo==%%==* %=X  OOOOOOOOOOOOO",
"OOOOOOOOOOOOoO=====* X==X* @OOOOOOOOOOOO",
"OOOOOOOOOOOO&=====* %====% $OOOOOOOOOOOO",
"OOOOOOOOOOOoo====  X=====%* OOOOOOOOOOOO",
"OOOOOOOOOOOo+===* *%*%%==X* @OOOOOOOOOOO",
"OOOOOOOOOOO&====      %===% $OOOOOOOOOOO",
"OOOOOOOOOOO&==============%  OOOOOOOOOOO",
"OOOOOOOOOOO==============X%  @OOOOOOOOOO",
"OOOOOOOOOOO+%%%%%%%%%%%%%%   $OOOOOOOOOO",
"OOOOOOOOOOOOO%               $OOOOOOOOOO",
"OOOOOOOOOOOOO@               @OOOOOOOOOO",
"OOOOOOOOOOOOOO@$$$$$$$$$$$$$@OOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};
/* XPM */
static char *str_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 17 1",
/* colors */
"  c #000000",
". c #F8B090",
"X c #5C7A7A",
"o c #F87A24",
"O c #7C3400",
"+ c None",
"@ c #B0B0B0",
"# c #F89E6C",
"$ c #B64700",
"% c #909090",
"& c #606060",
"* c #CEAA90",
"= c #DADAB6",
"- c #303030",
"; c #F86800",
": c #FFB691",
"> c #F88C48",
/* pixels */
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"++++++++++++++++++++++++++++++++++++++++",
"+++++++++++++++++++*>*>#++++++++++++++++",
"++++++++++++++++*#o>..*#o*++++++++++++++",
"+++++++++++++++o#.#>.....o++++++++++++++",
"+++++++++++++++;>;#.o.>..#$X++++++++++++",
"+++++++++++++++o#>.o.>:...o  %++++++++++",
"++++++++++++++o##>>#o##>..#O -++++++++++",
"++++++++++++++>#.oo#>..>...O  ++++++++++",
"++++++++++++++*o##.>>;o#...o  ++++++++++",
"+++++++++++++++*;o#........>- &+++++++++",
"+++++++++++++++++#>>;o......O -+++++++++",
"+++++++++++++++++@+@+o>.....$  +++++++++",
"+++++++++++++++++++++*;.#...>- %++++++++",
"++++++++++++++++++++++;>o....$ &++++++++",
"++++++++++++++++++++++#>>....>- %+++++++",
"+++++++++++++++++++++++;#>....; -+++++++",
"+++++++++++++++++++++++o#>....>O %++++++",
"+++++++++++++++++++++++*>o.....; -++++++",
"+++++++++++++#>**+++++++;#.....>O %+++++",
"+o#+++++++*o;>>>>o#+++++o##.....; -+++++",
"+:#o*++++oo#..*..*>;*+++#>#.....>O %++++",
"+:=#o#+*;>.:==:....#;*++@o.......; &++++",
"+::..>;o#.=::::......o*++;.......>O ++++",
"+.....#o.:.=:.........o#+;........$ ++++",
"+......#o..:...........#o;>.......o &+++",
"+........#..............*>o......:o- +++",
"+..................#o>#...#o.......O +++",
"+...............>o>#.......#>......O &++",
"+..................................o -++",
"+..................................>  ++",
"+..................................>  ++",
"+.................................#$  &+",
"+................................>$   &+",
"+..#>$o>#..............#>;>>>oOOO-    ++",
"+...#O  OOOOO$>>>>>>>$OO             %++",
"+...o                            -&&++++",
"+..#O                     -&&%++++++++++",
"++++++++++++++++++++++++++++++++++++++++"
};
/* XPM */
static char *stunned_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 12 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c #D4D4D4",
"O c None",
"+ c #B0B0B0",
"@ c #909090",
"# c #788C8C",
"$ c #606060",
"% c #406868",
"& c #303030",
"* c #6C91B6",
/* pixels */
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOO&$OOOO@OOO@@OO@OOOOOOOOOOOOO",
"OOOOOOOOOOO@& $OO@&&$$@ O@$$OOOOOOOOOOOO",
"OOOOOOOOOOOO$$ @@@$  &&OOO@$OOOOOOOOOOOO",
"OOOOOOOOOOOOO@@&$$$$&O$OO$O &@O@OOOOOOOO",
"OOOOOO@@@@@@OO@$$O$&$@@OO&  &&$O&OOOOOOO",
"OOOOOO&&&& & $ &&@$ &O@$& &&&$ & $OOOOOO",
"OOOOOO$&OO &&&$ $$    $&  $$&$&&&OOOOOOO",
"OOOOOO@@O@$  &+ #       &O$$  $$&O@OOOOO",
"OOOOOOOO@X%$ %&   %%    & &&  $$@@@@OOOO",
"OOOOOOO+$$@+     &%%%&%&   &  &@OOO&&OOO",
"OOOOOO.Xo%+      &&%%%%%&& &   OO@$&&OOO",
"OOOOO++ $$&&$     && %&%%&    &O@&$&OOOO",
"OOOOO####$ X&&& &&     &%&   &    &&OOOO",
"OOOO++#.+## $&# %& &       &     &$ OOOO",
"OOOO#+++.@&%&& &#&%&   &       $ @OOOOOO",
"OOOO##....#+$#@%#& $%$&@&$$% & X##$@OOOO",
"OOOO.+#+.+@#+#+$&$X#%&%.+& %&#++.$&OOOOO",
"OOOOO#+#+.+++#$$%&++&X+X#&#+&+&##+ &OOOO",
"OOOOO#..#OO#+@%#o##X.@..++.+$&+#+#& @OOO",
"OOOOO+#.#O+#+#O@++@$$##+##++###+.#& $OOO",
"OOOOOOXX+#+#+#o.@%&$++#+..##.#+###  &OOO",
"OOOOOOOX#.#X+#+#+##&#+..+####%XX%%   OOO",
"OOOOOOOO+%%X.#+#+#.++#+#+#+.X++*.%  &OOO",
"OOOOOOOOO@& &##+#+.O####.+XX%%%%#%  $OOO",
"OOOOOOOOOOO.   %X.+.#+++XXX*.+++#X  $OOO",
"OOOOOOOOOOOO@&   %%X..#X%#.####%X&  $OOO",
"OOOOOOOOOOOOOO@$ &XX%%%*.#X%###*&   OOOO",
"OOOOOOOOOOOOOOOOOO+%%%*%%#.+.#*&   @OOOO",
"OOOOOOOOOOOOOOOOOOO*%%%**X##X%&    OOOOO",
"OOOOOOOOOOOOOOOOOOOOX%%%%X*X&     @OOOOO",
"OOOOOOOOOOOOOOOOOOOOX%%%%X      &@OOOOOO",
"OOOOOOOOOOOOOOOOOOOO*%%%X&   &$$OOOOOOOO",
"OOOOOOOOOOOOOOOOOOOO+X%%*  @OOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOX%%&  OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOO*%%% $OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOO*%%% $OOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOO.X%& $OOOOOOOOOOOOO"
};
/* XPM */
static char *wis_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c None",
"O c #B0B0B0",
"+ c #909090",
"@ c #788C8C",
"# c #606060",
"$ c #406868",
"% c #FFFFFF",
"& c #303030",
"* c #6C91B6",
"= c #0000FF",
/* pixels */
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooo+#& &#oooooooooooooooooooo",
"oooooooooooo+&       #oooooooooooooooooo",
"ooooooooooo+  &====&& &ooooooooooooooooo",
"oooooooooo+ &==&  ===%& +ooooooooooooooo",
"ooooooooo+&%===   ===%%o&&oooooooooooooo",
"oooooooo.&%%===&  ===%o&   #+ooooooooooo",
"oooo&###&&%%*=======$#&ooo#&  #+oooooooo",
"ooooo###o+&X$=====& #oo##oooo+######oooo",
"oooooooooooo######@oo##ooooooooooooooooo",
"oooooooooooooOoOoOo##ooooooooooooooooooo",
"ooooooooooooooooo+#+ooo+&#oooooooooooooo",
"ooooooooooooooooooooooo#oooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo"
};
/* XPM */
static char *nothing_xpm[] = {
/* width height ncolors chars_per_pixel */
"40 40 13 1",
/* colors */
"  c #000000",
". c #949E9E",
"X c #5C7A7A",
"o c None",
"O c #B0B0B0",
"+ c #909090",
"@ c #788C8C",
"# c #606060",
"$ c #406868",
"% c #FFFFFF",
"& c #303030",
"* c #6C91B6",
"= c #0000FF",
/* pixels */
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooo"
};
/* clang-format on */
