/* NetHack 3.7 sfproto.h	Sat Jun 22 22:53:12 2019 */
/* Copyright (c) NetHack Development Team 2018.                   */
/* NetHack may be freely redistributed.  See license for details. */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE!          */

#ifndef SFPROTO_H
#define SFPROTO_H

#include "hack.h"
#include "integer.h"
#include "wintype.h"

#define E extern

E int NDECL(critical_members_count);
/* sfbase.c output functions */
E void FDECL(sfo_addinfo, (NHFILE *, const char *, const char *, const char *, int));
E void FDECL(sfo_aligntyp, (NHFILE *, aligntyp *, const char *, const char *, int));
E void FDECL(sfo_any, (NHFILE *, anything *, const char *, const char *, int));
E void FDECL(sfo_bitfield, (NHFILE *, uint8_t *, const char *, const char *, int));
E void FDECL(sfo_boolean, (NHFILE *, boolean *, const char *, const char *, int));
E void FDECL(sfo_char, (NHFILE *, const char *, const char *, const char *, int));
E void FDECL(sfo_genericptr, (NHFILE *, genericptr_t *, const char *, const char *, int));
E void FDECL(sfo_int, (NHFILE *, int *, const char *, const char *, int));
E void FDECL(sfo_long, (NHFILE *, long *, const char *, const char *, int));
E void FDECL(sfo_schar, (NHFILE *, schar *, const char *, const char *, int));
E void FDECL(sfo_short, (NHFILE *, short *, const char *, const char *, int));
E void FDECL(sfo_size_t, (NHFILE *, size_t *, const char *, const char *, int));
E void FDECL(sfo_time_t, (NHFILE *, time_t *, const char *, const char *, int));
E void FDECL(sfo_uchar, (NHFILE *, uchar *, const char *, const char *, int));
E void FDECL(sfo_unsigned, (NHFILE *, unsigned *, const char *, const char *, int));
E void FDECL(sfo_uchar, (NHFILE *, unsigned char *, const char *, const char *, int));
E void FDECL(sfo_uint, (NHFILE *, unsigned int *, const char *, const char *, int));
E void FDECL(sfo_ulong, (NHFILE *, unsigned long *, const char *, const char *, int));
E void FDECL(sfo_ushort, (NHFILE *, unsigned short *, const char *, const char *, int));
E void FDECL(sfo_xchar, (NHFILE *, xchar *, const char *, const char *, int));
E void FDECL(sfo_str, (NHFILE *, const char *, const char *, const char *, int));
/* sfbase.c input functions */
E void FDECL(sfi_addinfo, (NHFILE *, const char *, const char *, const char *, int));
E void FDECL(sfi_aligntyp, (NHFILE *, aligntyp *, const char *, const char *, int));
E void FDECL(sfi_any, (NHFILE *, anything *, const char *, const char *, int));
E void FDECL(sfi_bitfield, (NHFILE *, uint8_t *, const char *, const char *, int));
E void FDECL(sfi_boolean, (NHFILE *, boolean *, const char *, const char *, int));
E void FDECL(sfi_char, (NHFILE *, const char *, const char *, const char *, int));
E void FDECL(sfi_genericptr, (NHFILE *, genericptr_t *, const char *, const char *, int));
E void FDECL(sfi_int, (NHFILE *, int *, const char *, const char *, int));
E void FDECL(sfi_long, (NHFILE *, long *, const char *, const char *, int));
E void FDECL(sfi_schar, (NHFILE *, schar *, const char *, const char *, int));
E void FDECL(sfi_short, (NHFILE *, short *, const char *, const char *, int));
E void FDECL(sfi_size_t, (NHFILE *, size_t *, const char *, const char *, int));
E void FDECL(sfi_time_t, (NHFILE *, time_t *, const char *, const char *, int));
E void FDECL(sfi_uchar, (NHFILE *, uchar *, const char *, const char *, int));
E void FDECL(sfi_unsigned, (NHFILE *, unsigned *, const char *, const char *, int));
E void FDECL(sfi_uchar, (NHFILE *, unsigned char *, const char *, const char *, int));
E void FDECL(sfi_uint, (NHFILE *, unsigned int *, const char *, const char *, int));
E void FDECL(sfi_ulong, (NHFILE *, unsigned long *, const char *, const char *, int));
E void FDECL(sfi_ushort, (NHFILE *, unsigned short *, const char *, const char *, int));
E void FDECL(sfi_xchar, (NHFILE *, xchar *, const char *, const char *, int));
E void FDECL(sfi_str, (NHFILE *, const char *, const char *, const char *, int));
/* generated output functions */
E void FDECL(sfo_align, (NHFILE *, struct align *, const char *, const char *, int));
E void FDECL(sfo_attribs, (NHFILE *, struct attribs *, const char *, const char *, int));
E void FDECL(sfo_bill_x, (NHFILE *, struct bill_x *, const char *, const char *, int));
E void FDECL(sfo_book_info, (NHFILE *, struct book_info *, const char *, const char *, int));
E void FDECL(sfo_branch, (NHFILE *, struct branch *, const char *, const char *, int));
E void FDECL(sfo_bubble, (NHFILE *, struct bubble *, const char *, const char *, int));
E void FDECL(sfo_cemetery, (NHFILE *, struct cemetery *, const char *, const char *, int));
E void FDECL(sfo_context_info, (NHFILE *, struct context_info *, const char *, const char *, int));
E void FDECL(sfo_d_flags, (NHFILE *, struct d_flags *, const char *, const char *, int));
E void FDECL(sfo_d_level, (NHFILE *, struct d_level *, const char *, const char *, int));
E void FDECL(sfo_damage, (NHFILE *, struct damage *, const char *, const char *, int));
E void FDECL(sfo_dest_area, (NHFILE *, struct dest_area *, const char *, const char *, int));
E void FDECL(sfo_dgn_topology, (NHFILE *, struct dgn_topology *, const char *, const char *, int));
E void FDECL(sfo_dig_info, (NHFILE *, struct dig_info *, const char *, const char *, int));
E void FDECL(sfo_dungeon, (NHFILE *, struct dungeon *, const char *, const char *, int));
E void FDECL(sfo_edog, (NHFILE *, struct edog *, const char *, const char *, int));
E void FDECL(sfo_egd, (NHFILE *, struct egd *, const char *, const char *, int));
E void FDECL(sfo_emin, (NHFILE *, struct emin *, const char *, const char *, int));
E void FDECL(sfo_engr, (NHFILE *, struct engr *, const char *, const char *, int));
E void FDECL(sfo_epri, (NHFILE *, struct epri *, const char *, const char *, int));
E void FDECL(sfo_eshk, (NHFILE *, struct eshk *, const char *, const char *, int));
E void FDECL(sfo_fakecorridor, (NHFILE *, struct fakecorridor *, const char *, const char *, int));
E void FDECL(sfo_fe, (NHFILE *, struct fe *, const char *, const char *, int));
E void FDECL(sfo_flag, (NHFILE *, struct flag *, const char *, const char *, int));
E void FDECL(sfo_fruit, (NHFILE *, struct fruit *, const char *, const char *, int));
E void FDECL(sfo_kinfo, (NHFILE *, struct kinfo *, const char *, const char *, int));
E void FDECL(sfo_levelflags, (NHFILE *, struct levelflags *, const char *, const char *, int));
E void FDECL(sfo_linfo, (NHFILE *, struct linfo *, const char *, const char *, int));
E void FDECL(sfo_ls_t, (NHFILE *, struct ls_t *, const char *, const char *, int));
E void FDECL(sfo_mapseen_feat, (NHFILE *, struct mapseen_feat *, const char *, const char *, int));
E void FDECL(sfo_mapseen_flags, (NHFILE *, struct mapseen_flags *, const char *, const char *, int));
E void FDECL(sfo_mapseen_rooms, (NHFILE *, struct mapseen_rooms *, const char *, const char *, int));
E void FDECL(sfo_mapseen, (NHFILE *, struct mapseen *, const char *, const char *, int));
E void FDECL(sfo_mextra, (NHFILE *, struct mextra *, const char *, const char *, int));
E void FDECL(sfo_mkroom, (NHFILE *, struct mkroom *, const char *, const char *, int));
E void FDECL(sfo_monst, (NHFILE *, struct monst *, const char *, const char *, int));
E void FDECL(sfo_mvitals, (NHFILE *, struct mvitals *, const char *, const char *, int));
E void FDECL(sfo_nhcoord, (NHFILE *, struct nhcoord *, const char *, const char *, int));
E void FDECL(sfo_nhrect, (NHFILE *, struct nhrect *, const char *, const char *, int));
E void FDECL(sfo_novel_tracking, (NHFILE *, struct novel_tracking *, const char *, const char *, int));
E void FDECL(sfo_obj, (NHFILE *, struct obj *, const char *, const char *, int));
E void FDECL(sfo_objclass, (NHFILE *, struct objclass *, const char *, const char *, int));
E void FDECL(sfo_obj_split, (NHFILE *, struct obj_split *, const char *, const char *, int));
E void FDECL(sfo_oextra, (NHFILE *, struct oextra *, const char *, const char *, int));
E void FDECL(sfo_polearm_info, (NHFILE *, struct polearm_info *, const char *, const char *, int));
E void FDECL(sfo_prop, (NHFILE *, struct prop *, const char *, const char *, int));
E void FDECL(sfo_q_score, (NHFILE *, struct q_score *, const char *, const char *, int));
E void FDECL(sfo_rm, (NHFILE *, struct rm *, const char *, const char *, int));
E void FDECL(sfo_s_level, (NHFILE *, struct s_level *, const char *, const char *, int));
E void FDECL(sfo_savefile_info, (NHFILE *, struct savefile_info *, const char *, const char *, int));
E void FDECL(sfo_skills, (NHFILE *, struct skills *, const char *, const char *, int));
E void FDECL(sfo_spell, (NHFILE *, struct spell *, const char *, const char *, int));
E void FDECL(sfo_stairway, (NHFILE *, struct stairway *, const char *, const char *, int));
E void FDECL(sfo_takeoff_info, (NHFILE *, struct takeoff_info *, const char *, const char *, int));
E void FDECL(sfo_tin_info, (NHFILE *, struct tin_info *, const char *, const char *, int));
E void FDECL(sfo_trap, (NHFILE *, struct trap *, const char *, const char *, int));
E void FDECL(sfo_tribute_info, (NHFILE *, struct tribute_info *, const char *, const char *, int));
E void FDECL(sfo_u_achieve, (NHFILE *, struct u_achieve *, const char *, const char *, int));
E void FDECL(sfo_u_conduct, (NHFILE *, struct u_conduct *, const char *, const char *, int));
E void FDECL(sfo_u_event, (NHFILE *, struct u_event *, const char *, const char *, int));
E void FDECL(sfo_u_have, (NHFILE *, struct u_have *, const char *, const char *, int));
E void FDECL(sfo_u_realtime, (NHFILE *, struct u_realtime *, const char *, const char *, int));
E void FDECL(sfo_u_roleplay, (NHFILE *, struct u_roleplay *, const char *, const char *, int));
E void FDECL(sfo_version_info, (NHFILE *, struct version_info *, const char *, const char *, int));
E void FDECL(sfo_victual_info, (NHFILE *, struct victual_info *, const char *, const char *, int));
E void FDECL(sfo_vlaunchinfo, (NHFILE *, union vlaunchinfo *, const char *, const char *, int));
E void FDECL(sfo_vptrs, (NHFILE *, union vptrs *, const char *, const char *, int));
E void FDECL(sfo_warntype_info, (NHFILE *, struct warntype_info *, const char *, const char *, int));
E void FDECL(sfo_you, (NHFILE *, struct you *, const char *, const char *, int));
/* generated input functions */
E void FDECL(sfi_align, (NHFILE *, struct align *, const char *, const char *, int));
E void FDECL(sfi_attribs, (NHFILE *, struct attribs *, const char *, const char *, int));
E void FDECL(sfi_bill_x, (NHFILE *, struct bill_x *, const char *, const char *, int));
E void FDECL(sfi_book_info, (NHFILE *, struct book_info *, const char *, const char *, int));
E void FDECL(sfi_branch, (NHFILE *, struct branch *, const char *, const char *, int));
E void FDECL(sfi_bubble, (NHFILE *, struct bubble *, const char *, const char *, int));
E void FDECL(sfi_cemetery, (NHFILE *, struct cemetery *, const char *, const char *, int));
E void FDECL(sfi_context_info, (NHFILE *, struct context_info *, const char *, const char *, int));
E void FDECL(sfi_d_flags, (NHFILE *, struct d_flags *, const char *, const char *, int));
E void FDECL(sfi_d_level, (NHFILE *, struct d_level *, const char *, const char *, int));
E void FDECL(sfi_damage, (NHFILE *, struct damage *, const char *, const char *, int));
E void FDECL(sfi_dest_area, (NHFILE *, struct dest_area *, const char *, const char *, int));
E void FDECL(sfi_dgn_topology, (NHFILE *, struct dgn_topology *, const char *, const char *, int));
E void FDECL(sfi_dig_info, (NHFILE *, struct dig_info *, const char *, const char *, int));
E void FDECL(sfi_dungeon, (NHFILE *, struct dungeon *, const char *, const char *, int));
E void FDECL(sfi_edog, (NHFILE *, struct edog *, const char *, const char *, int));
E void FDECL(sfi_egd, (NHFILE *, struct egd *, const char *, const char *, int));
E void FDECL(sfi_emin, (NHFILE *, struct emin *, const char *, const char *, int));
E void FDECL(sfi_engr, (NHFILE *, struct engr *, const char *, const char *, int));
E void FDECL(sfi_epri, (NHFILE *, struct epri *, const char *, const char *, int));
E void FDECL(sfi_eshk, (NHFILE *, struct eshk *, const char *, const char *, int));
E void FDECL(sfi_fakecorridor, (NHFILE *, struct fakecorridor *, const char *, const char *, int));
E void FDECL(sfi_fe, (NHFILE *, struct fe *, const char *, const char *, int));
E void FDECL(sfi_flag, (NHFILE *, struct flag *, const char *, const char *, int));
E void FDECL(sfi_fruit, (NHFILE *, struct fruit *, const char *, const char *, int));
E void FDECL(sfi_kinfo, (NHFILE *, struct kinfo *, const char *, const char *, int));
E void FDECL(sfi_levelflags, (NHFILE *, struct levelflags *, const char *, const char *, int));
E void FDECL(sfi_linfo, (NHFILE *, struct linfo *, const char *, const char *, int));
E void FDECL(sfi_ls_t, (NHFILE *, struct ls_t *, const char *, const char *, int));
E void FDECL(sfi_mapseen_feat, (NHFILE *, struct mapseen_feat *, const char *, const char *, int));
E void FDECL(sfi_mapseen_flags, (NHFILE *, struct mapseen_flags *, const char *, const char *, int));
E void FDECL(sfi_mapseen_rooms, (NHFILE *, struct mapseen_rooms *, const char *, const char *, int));
E void FDECL(sfi_mapseen, (NHFILE *, struct mapseen *, const char *, const char *, int));
E void FDECL(sfi_mextra, (NHFILE *, struct mextra *, const char *, const char *, int));
E void FDECL(sfi_mkroom, (NHFILE *, struct mkroom *, const char *, const char *, int));
E void FDECL(sfi_monst, (NHFILE *, struct monst *, const char *, const char *, int));
E void FDECL(sfi_mvitals, (NHFILE *, struct mvitals *, const char *, const char *, int));
E void FDECL(sfi_nhcoord, (NHFILE *, struct nhcoord *, const char *, const char *, int));
E void FDECL(sfi_nhrect, (NHFILE *, struct nhrect *, const char *, const char *, int));
E void FDECL(sfi_novel_tracking, (NHFILE *, struct novel_tracking *, const char *, const char *, int));
E void FDECL(sfi_obj, (NHFILE *, struct obj *, const char *, const char *, int));
E void FDECL(sfi_objclass, (NHFILE *, struct objclass *, const char *, const char *, int));
E void FDECL(sfi_obj_split, (NHFILE *, struct obj_split *, const char *, const char *, int));
E void FDECL(sfi_oextra, (NHFILE *, struct oextra *, const char *, const char *, int));
E void FDECL(sfi_polearm_info, (NHFILE *, struct polearm_info *, const char *, const char *, int));
E void FDECL(sfi_prop, (NHFILE *, struct prop *, const char *, const char *, int));
E void FDECL(sfi_q_score, (NHFILE *, struct q_score *, const char *, const char *, int));
E void FDECL(sfi_rm, (NHFILE *, struct rm *, const char *, const char *, int));
E void FDECL(sfi_s_level, (NHFILE *, struct s_level *, const char *, const char *, int));
E void FDECL(sfi_savefile_info, (NHFILE *, struct savefile_info *, const char *, const char *, int));
E void FDECL(sfi_skills, (NHFILE *, struct skills *, const char *, const char *, int));
E void FDECL(sfi_spell, (NHFILE *, struct spell *, const char *, const char *, int));
E void FDECL(sfi_stairway, (NHFILE *, struct stairway *, const char *, const char *, int));
E void FDECL(sfi_takeoff_info, (NHFILE *, struct takeoff_info *, const char *, const char *, int));
E void FDECL(sfi_tin_info, (NHFILE *, struct tin_info *, const char *, const char *, int));
E void FDECL(sfi_trap, (NHFILE *, struct trap *, const char *, const char *, int));
E void FDECL(sfi_tribute_info, (NHFILE *, struct tribute_info *, const char *, const char *, int));
E void FDECL(sfi_u_achieve, (NHFILE *, struct u_achieve *, const char *, const char *, int));
E void FDECL(sfi_u_conduct, (NHFILE *, struct u_conduct *, const char *, const char *, int));
E void FDECL(sfi_u_event, (NHFILE *, struct u_event *, const char *, const char *, int));
E void FDECL(sfi_u_have, (NHFILE *, struct u_have *, const char *, const char *, int));
E void FDECL(sfi_u_realtime, (NHFILE *, struct u_realtime *, const char *, const char *, int));
E void FDECL(sfi_u_roleplay, (NHFILE *, struct u_roleplay *, const char *, const char *, int));
E void FDECL(sfi_version_info, (NHFILE *, struct version_info *, const char *, const char *, int));
E void FDECL(sfi_victual_info, (NHFILE *, struct victual_info *, const char *, const char *, int));
E void FDECL(sfi_vlaunchinfo, (NHFILE *, union vlaunchinfo *, const char *, const char *, int));
E void FDECL(sfi_vptrs, (NHFILE *, union vptrs *, const char *, const char *, int));
E void FDECL(sfi_warntype_info, (NHFILE *, struct warntype_info *, const char *, const char *, int));
E void FDECL(sfi_you, (NHFILE *, struct you *, const char *, const char *, int));
#endif /* SFPROTO_H */
