#!/usr/bin/perl
# NetHack 3.6  NHadd       $NHDT-Date: 1524689631 2018/04/25 20:53:51 $  $NHDT-Branch: NetHack-3.6.0 $:$NHDT-Revision: 1.1 $
# Copyright (c) 2015 by Kenneth Lorber, Kensington, Maryland
# NetHack may be freely redistributed.  See license for details.

# wrapper for nhadd and nhcommit aliases

%ok = map { $_ => 1 } ('add', 'commit');

die "Bad subcommand '$ARGV[0]'" unless $ok{$ARGV[0]};

# we won't fail on a failure, so just system()
$rv = system('.git/hooks/nhsub',"--$ARGV[0]",@ARGV[1..$#ARGV]);
if($rv){
        print "warning: nhsub failed: $rv $!\n";
}

if(length $ENV{GIT_PREFIX}){
        chdir($ENV{GIT_PREFIX}) or die "Can't chdir $ENV{GIT_PREFIX}: $!";
}

exec "git", @ARGV or die "Can't exec git: $!";
