#!/usr/bin/perl
# $NHDT-Date: 1524683721 2018/04/25 19:15:21 $ $NHDT-Branch: NetHack-3.6.0 $:$NHDT-Revision: 1.1 $

#STARTUP-START
BEGIN {
    # OS hackery has to be duplicated in each of the hooks :/
    # first the directory separator
    my $DS = quotemeta('/');
    my $PDS = '/';
    # msys: POSIXish over a Windows filesystem (so / not \ but \r\n not \n).
    # temporarily removed because inconsistent behavior
    # if ($^O eq "msys")
    # {
    #   $/ = "\r\n";
    #   $\ = "\r\n";
    # }
    if($^O eq "MSWin32"){
        $DS = quotemeta('\\');
	$PDS = '\\';
    }
    $gitdir = `git rev-parse --git-dir`;
    chomp $gitdir;
    push(@INC, $gitdir.$PDS."hooks");
}
use NHgithook;
#STARTUP-END

&NHgithook::PRE;
&NHgithook::nhversioning;
&NHgithook::POST;
exit 0;
