/* nhlua.h - generated by top Makefile */
#include "../lib/lua544/src/lua.h"
LUA_API int   (lua_error) (lua_State *L) NORETURN;
#include "../lib/lua544/src/lualib.h"
#include "../lib/lua544/src/lauxlib.h"
/*nhlua.h*/
